# Copyright (c) 2026 Vincent Mayeski / M2 Tech (16425640 Canada Inc.).
# Contact: mayeski@gmail.com | https://www.linkedin.com/in/vmayeski/
#
# Licensed under the MIT License. See LICENSE file in the project root.

include $(KSPRPROJ)/mk_kaspr/glob_begin.mk

# sim/include holds the SimKaspr header
EXTRA_INCL = -I$(KSPRPROJ)/sim/include

SRC = SimKaspr.cpp SlippageProbe.cpp main.cpp
APPNAM = sim

include $(KSPRPROJ)/mk_kaspr/app_template.mk
