# Copyright (c) 2026 Vincent Mayeski / M2 Tech (16425640 Canada Inc.).
# Contact: mayeski@gmail.com | https://www.linkedin.com/in/vmayeski/
#
# Licensed under the MIT License. See LICENSE file in the project root.

include $(KSPRPROJ)/mk_kaspr/glob_begin.mk

SRC = binstats.cpp
APPNAM = binstats

# zlib comes in via chutil; no extra libraries needed

include $(KSPRPROJ)/mk_kaspr/app_template.mk
