# Copyright (c) 2026 Vincent Mayeski / M2 Tech (16425640 Canada Inc.).
#
# Licensed under the MIT License. See LICENSE file in the project root.

NAM=positionman

include $(KSPRPROJ)/mk_kaspr/glob_begin.mk

EXTRA_INCL=-I$(KSPRPROJ)/positionman/include

LIBSRC = PositionManager.cpp

include $(KSPRPROJ)/mk_kaspr/lib_template.mk
