// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct alpha {
    std::uint32_t value;
    enum {
        UNI,
        tim,
        theta,
        theta_d2,
        mid_d,
        mid80,
        mid35,
        mid15,
        wmid3,
        wmid5,
        wmid10,
        wmid3_fen,
        wmid5_fen,
        wmid10_fen,
        wmid3_btec,
        wmid5_btec,
        wmid10_btec,
        fenics_sz_3,
        fenics_sz_5,
        fenics_sz_10,
        btec_sz_3,
        btec_sz_5,
        btec_sz_10,
        bo,
        bar,
        bar01,
        mid,
        stddev10,
        num_trad,
        bs,
        as,
        bb,
        ba,
        cum_tx_sz,
        pred,
        stddev,
        model_name,
        index,
        bos,
        th1a,
        th2a,
        th3a,
        th1s,
        th2s,
        th3s,
        bb_fenics_clob,
        ba_fenics_clob,
        bs_fenics_clob,
        as_fenics_clob,
        bb_fenics_glob,
        ba_fenics_glob,
        bs_fenics_glob,
        as_fenics_glob,
        thp,
        rng,
        vol,
        nof_3ms,
        nof_3ms_mom,
        nof_5ms,
        nof_5ms_mom,
        nof_10ms,
        nof_10ms_mom,
        nof_100ms,
        nof_100ms_mom,
        nof_ovr_3ms,
        nof_ovr_3ms_mom,
        nof_ovr_5ms,
        nof_ovr_5ms_mom,
        nof_ovr_10ms,
        nof_ovr_10ms_mom,
        nof_ovr_100ms,
        nof_ovr_100ms_mom
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr alpha() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr alpha(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for alpha
inline constexpr std::array<const char*, 72> alpha_names = {{
    "UNI",
    "tim",
    "theta",
    "theta_d2",
    "mid_d",
    "mid80",
    "mid35",
    "mid15",
    "wmid3",
    "wmid5",
    "wmid10",
    "wmid3_fen",
    "wmid5_fen",
    "wmid10_fen",
    "wmid3_btec",
    "wmid5_btec",
    "wmid10_btec",
    "fenics_sz_3",
    "fenics_sz_5",
    "fenics_sz_10",
    "btec_sz_3",
    "btec_sz_5",
    "btec_sz_10",
    "bo",
    "bar",
    "bar01",
    "mid",
    "stddev10",
    "num_trad",
    "bs",
    "as",
    "bb",
    "ba",
    "cum_tx_sz",
    "pred",
    "stddev",
    "model_name",
    "index",
    "bos",
    "th1a",
    "th2a",
    "th3a",
    "th1s",
    "th2s",
    "th3s",
    "bb_fenics_clob",
    "ba_fenics_clob",
    "bs_fenics_clob",
    "as_fenics_clob",
    "bb_fenics_glob",
    "ba_fenics_glob",
    "bs_fenics_glob",
    "as_fenics_glob",
    "thp",
    "rng",
    "vol",
    "nof_3ms",
    "nof_3ms_mom",
    "nof_5ms",
    "nof_5ms_mom",
    "nof_10ms",
    "nof_10ms_mom",
    "nof_100ms",
    "nof_100ms_mom",
    "nof_ovr_3ms",
    "nof_ovr_3ms_mom",
    "nof_ovr_5ms",
    "nof_ovr_5ms_mom",
    "nof_ovr_10ms",
    "nof_ovr_10ms_mom",
    "nof_ovr_100ms",
    "nof_ovr_100ms_mom",
}};

inline constexpr std::array<std::uint32_t, 72> alpha_values = {{
    alpha::UNI,
    alpha::tim,
    alpha::theta,
    alpha::theta_d2,
    alpha::mid_d,
    alpha::mid80,
    alpha::mid35,
    alpha::mid15,
    alpha::wmid3,
    alpha::wmid5,
    alpha::wmid10,
    alpha::wmid3_fen,
    alpha::wmid5_fen,
    alpha::wmid10_fen,
    alpha::wmid3_btec,
    alpha::wmid5_btec,
    alpha::wmid10_btec,
    alpha::fenics_sz_3,
    alpha::fenics_sz_5,
    alpha::fenics_sz_10,
    alpha::btec_sz_3,
    alpha::btec_sz_5,
    alpha::btec_sz_10,
    alpha::bo,
    alpha::bar,
    alpha::bar01,
    alpha::mid,
    alpha::stddev10,
    alpha::num_trad,
    alpha::bs,
    alpha::as,
    alpha::bb,
    alpha::ba,
    alpha::cum_tx_sz,
    alpha::pred,
    alpha::stddev,
    alpha::model_name,
    alpha::index,
    alpha::bos,
    alpha::th1a,
    alpha::th2a,
    alpha::th3a,
    alpha::th1s,
    alpha::th2s,
    alpha::th3s,
    alpha::bb_fenics_clob,
    alpha::ba_fenics_clob,
    alpha::bs_fenics_clob,
    alpha::as_fenics_clob,
    alpha::bb_fenics_glob,
    alpha::ba_fenics_glob,
    alpha::bs_fenics_glob,
    alpha::as_fenics_glob,
    alpha::thp,
    alpha::rng,
    alpha::vol,
    alpha::nof_3ms,
    alpha::nof_3ms_mom,
    alpha::nof_5ms,
    alpha::nof_5ms_mom,
    alpha::nof_10ms,
    alpha::nof_10ms_mom,
    alpha::nof_100ms,
    alpha::nof_100ms_mom,
    alpha::nof_ovr_3ms,
    alpha::nof_ovr_3ms_mom,
    alpha::nof_ovr_5ms,
    alpha::nof_ovr_5ms_mom,
    alpha::nof_ovr_10ms,
    alpha::nof_ovr_10ms_mom,
    alpha::nof_ovr_100ms,
    alpha::nof_ovr_100ms_mom,
}};

using alpha_pair = std::pair<alpha, const char*>;

inline constexpr std::array<alpha_pair, 72> alpha_name_hash = {{
    alpha_pair{alpha::UNI, "UNI"},
    alpha_pair{alpha::tim, "tim"},
    alpha_pair{alpha::theta, "theta"},
    alpha_pair{alpha::theta_d2, "theta_d2"},
    alpha_pair{alpha::mid_d, "mid_d"},
    alpha_pair{alpha::mid80, "mid80"},
    alpha_pair{alpha::mid35, "mid35"},
    alpha_pair{alpha::mid15, "mid15"},
    alpha_pair{alpha::wmid3, "wmid3"},
    alpha_pair{alpha::wmid5, "wmid5"},
    alpha_pair{alpha::wmid10, "wmid10"},
    alpha_pair{alpha::wmid3_fen, "wmid3_fen"},
    alpha_pair{alpha::wmid5_fen, "wmid5_fen"},
    alpha_pair{alpha::wmid10_fen, "wmid10_fen"},
    alpha_pair{alpha::wmid3_btec, "wmid3_btec"},
    alpha_pair{alpha::wmid5_btec, "wmid5_btec"},
    alpha_pair{alpha::wmid10_btec, "wmid10_btec"},
    alpha_pair{alpha::fenics_sz_3, "fenics_sz_3"},
    alpha_pair{alpha::fenics_sz_5, "fenics_sz_5"},
    alpha_pair{alpha::fenics_sz_10, "fenics_sz_10"},
    alpha_pair{alpha::btec_sz_3, "btec_sz_3"},
    alpha_pair{alpha::btec_sz_5, "btec_sz_5"},
    alpha_pair{alpha::btec_sz_10, "btec_sz_10"},
    alpha_pair{alpha::bo, "bo"},
    alpha_pair{alpha::bar, "bar"},
    alpha_pair{alpha::bar01, "bar01"},
    alpha_pair{alpha::mid, "mid"},
    alpha_pair{alpha::stddev10, "stddev10"},
    alpha_pair{alpha::num_trad, "num_trad"},
    alpha_pair{alpha::bs, "bs"},
    alpha_pair{alpha::as, "as"},
    alpha_pair{alpha::bb, "bb"},
    alpha_pair{alpha::ba, "ba"},
    alpha_pair{alpha::cum_tx_sz, "cum_tx_sz"},
    alpha_pair{alpha::pred, "pred"},
    alpha_pair{alpha::stddev, "stddev"},
    alpha_pair{alpha::model_name, "model_name"},
    alpha_pair{alpha::index, "index"},
    alpha_pair{alpha::bos, "bos"},
    alpha_pair{alpha::th1a, "th1a"},
    alpha_pair{alpha::th2a, "th2a"},
    alpha_pair{alpha::th3a, "th3a"},
    alpha_pair{alpha::th1s, "th1s"},
    alpha_pair{alpha::th2s, "th2s"},
    alpha_pair{alpha::th3s, "th3s"},
    alpha_pair{alpha::bb_fenics_clob, "bb_fenics_clob"},
    alpha_pair{alpha::ba_fenics_clob, "ba_fenics_clob"},
    alpha_pair{alpha::bs_fenics_clob, "bs_fenics_clob"},
    alpha_pair{alpha::as_fenics_clob, "as_fenics_clob"},
    alpha_pair{alpha::bb_fenics_glob, "bb_fenics_glob"},
    alpha_pair{alpha::ba_fenics_glob, "ba_fenics_glob"},
    alpha_pair{alpha::bs_fenics_glob, "bs_fenics_glob"},
    alpha_pair{alpha::as_fenics_glob, "as_fenics_glob"},
    alpha_pair{alpha::thp, "thp"},
    alpha_pair{alpha::rng, "rng"},
    alpha_pair{alpha::vol, "vol"},
    alpha_pair{alpha::nof_3ms, "nof_3ms"},
    alpha_pair{alpha::nof_3ms_mom, "nof_3ms_mom"},
    alpha_pair{alpha::nof_5ms, "nof_5ms"},
    alpha_pair{alpha::nof_5ms_mom, "nof_5ms_mom"},
    alpha_pair{alpha::nof_10ms, "nof_10ms"},
    alpha_pair{alpha::nof_10ms_mom, "nof_10ms_mom"},
    alpha_pair{alpha::nof_100ms, "nof_100ms"},
    alpha_pair{alpha::nof_100ms_mom, "nof_100ms_mom"},
    alpha_pair{alpha::nof_ovr_3ms, "nof_ovr_3ms"},
    alpha_pair{alpha::nof_ovr_3ms_mom, "nof_ovr_3ms_mom"},
    alpha_pair{alpha::nof_ovr_5ms, "nof_ovr_5ms"},
    alpha_pair{alpha::nof_ovr_5ms_mom, "nof_ovr_5ms_mom"},
    alpha_pair{alpha::nof_ovr_10ms, "nof_ovr_10ms"},
    alpha_pair{alpha::nof_ovr_10ms_mom, "nof_ovr_10ms_mom"},
    alpha_pair{alpha::nof_ovr_100ms, "nof_ovr_100ms"},
    alpha_pair{alpha::nof_ovr_100ms_mom, "nof_ovr_100ms_mom"},
}};

// Type-safe array indexed by alpha
template<typename T>
struct alpha_array {
    std::array<T, 72> data;

    // Access operators
    constexpr T& operator[](alpha idx) { return data[idx.value]; }
    constexpr const T& operator[](alpha idx) const { return data[idx.value]; }

    constexpr T& at(alpha idx) {
        if (idx.value >= data.size()) throw std::out_of_range("alpha_array::at");
        return data[idx.value];
    }
    constexpr const T& at(alpha idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("alpha_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for alpha

INLINE constexpr const char* to_string(alpha n) {
    if (static_cast<std::size_t>(n.value) < alpha_names.size()) {
        return alpha_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t alpha_num_syms() {
    return 72;
}

INLINE constexpr bool is_valid(alpha n) {
    return (n.value < alpha_num_syms() && n.value != alpha::UNI);
}

INLINE bool alpha_is_valid(std::string_view nam) {
    return std::find(alpha_names.begin(), alpha_names.end(), nam) != alpha_names.end();
}

INLINE alpha alpha_index_of(std::string_view str) {
    auto it = std::find(alpha_names.begin(), alpha_names.end(), str);
    if (it == alpha_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return alpha(static_cast<std::uint32_t>(it - alpha_names.begin()));
}

INLINE std::optional<alpha> alpha_try_parse(std::string_view str) {
    auto it = std::find(alpha_names.begin(), alpha_names.end(), str);
    if (it == alpha_names.end()) {
        return std::nullopt;
    }
    return alpha(static_cast<std::uint32_t>(it - alpha_names.begin()));
}

struct alpha_hash_t {
    bool contains(std::string_view key) const {
        return std::find(alpha_names.begin(), alpha_names.end(), key) != alpha_names.end();
    }
    alpha operator[](std::string_view key) const {
        return alpha_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(alpha_names.begin(), alpha_names.end(), key);
        if (it != alpha_names.end()) {
            return alpha_name_hash.begin() + (it - alpha_names.begin());
        }
        return alpha_name_hash.end();
    }
    auto end() const { return alpha_name_hash.end(); }
};
inline const alpha_hash_t alpha_hash;

// Operators for alpha

INLINE std::ostream& operator<<(std::ostream& out, const alpha& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::alpha> {
        std::size_t operator()(en::alpha e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
