// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct bs {
    std::uint32_t value;
    enum {
        BUY,
        SEL,
        UNK,
        UNI
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr bs() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr bs(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for bs
inline constexpr std::array<const char*, 4> bs_names = {{
    "BUY",
    "SEL",
    "UNK",
    "UNI",
}};

inline constexpr std::array<std::uint32_t, 4> bs_values = {{
    bs::BUY,
    bs::SEL,
    bs::UNK,
    bs::UNI,
}};

inline constexpr std::array<std::uint32_t, 3> bs_all = {{
    bs::BUY,
    bs::SEL,
    bs::UNK,
}};

using bs_pair = std::pair<bs, const char*>;

inline constexpr std::array<bs_pair, 4> bs_name_hash = {{
    bs_pair{bs::BUY, "BUY"},
    bs_pair{bs::SEL, "SEL"},
    bs_pair{bs::UNK, "UNK"},
    bs_pair{bs::UNI, "UNI"},
}};

// Type-safe array indexed by bs
template<typename T>
struct bs_array {
    std::array<T, 4> data;

    // Access operators
    constexpr T& operator[](bs idx) { return data[idx.value]; }
    constexpr const T& operator[](bs idx) const { return data[idx.value]; }

    constexpr T& at(bs idx) {
        if (idx.value >= data.size()) throw std::out_of_range("bs_array::at");
        return data[idx.value];
    }
    constexpr const T& at(bs idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("bs_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for bs

INLINE constexpr const char* to_string(bs n) {
    if (static_cast<std::size_t>(n.value) < bs_names.size()) {
        return bs_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t bs_num_syms() {
    return 4;
}

INLINE constexpr bool is_valid(bs n) {
    return (n.value < bs_num_syms() && n.value != bs::UNI);
}

INLINE bool bs_is_valid(std::string_view nam) {
    return std::find(bs_names.begin(), bs_names.end(), nam) != bs_names.end();
}

INLINE bs bs_index_of(std::string_view str) {
    auto it = std::find(bs_names.begin(), bs_names.end(), str);
    if (it == bs_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return bs(static_cast<std::uint32_t>(it - bs_names.begin()));
}

INLINE std::optional<bs> bs_try_parse(std::string_view str) {
    auto it = std::find(bs_names.begin(), bs_names.end(), str);
    if (it == bs_names.end()) {
        return std::nullopt;
    }
    return bs(static_cast<std::uint32_t>(it - bs_names.begin()));
}

struct bs_hash_t {
    bool contains(std::string_view key) const {
        return std::find(bs_names.begin(), bs_names.end(), key) != bs_names.end();
    }
    bs operator[](std::string_view key) const {
        return bs_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(bs_names.begin(), bs_names.end(), key);
        if (it != bs_names.end()) {
            return bs_name_hash.begin() + (it - bs_names.begin());
        }
        return bs_name_hash.end();
    }
    auto end() const { return bs_name_hash.end(); }
};
inline const bs_hash_t bs_hash;

// Operators for bs

INLINE std::ostream& operator<<(std::ostream& out, const bs& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::bs> {
        std::size_t operator()(en::bs e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
