// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct cal {
    std::uint32_t value;
    enum {
        NOEVENTS,
        USEOM,
        USEOM2,
        USMACRO,
        TESTING,
        OCCAM,
        OCCAMZNUB,
        OCCAMZN,
        OCCAMEOD,
        OCCAMEQ,
        ALLEVENTS,
        USEQOPEN,
        USEQCLOSE,
        USDAY,
        UNI
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr cal() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr cal(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for cal
inline constexpr std::array<const char*, 15> cal_names = {{
    "NOEVENTS",
    "USEOM",
    "USEOM2",
    "USMACRO",
    "TESTING",
    "OCCAM",
    "OCCAMZNUB",
    "OCCAMZN",
    "OCCAMEOD",
    "OCCAMEQ",
    "ALLEVENTS",
    "USEQOPEN",
    "USEQCLOSE",
    "USDAY",
    "UNI",
}};

inline constexpr std::array<std::uint32_t, 15> cal_values = {{
    cal::NOEVENTS,
    cal::USEOM,
    cal::USEOM2,
    cal::USMACRO,
    cal::TESTING,
    cal::OCCAM,
    cal::OCCAMZNUB,
    cal::OCCAMZN,
    cal::OCCAMEOD,
    cal::OCCAMEQ,
    cal::ALLEVENTS,
    cal::USEQOPEN,
    cal::USEQCLOSE,
    cal::USDAY,
    cal::UNI,
}};

inline constexpr std::array<std::uint32_t, 14> cal_all = {{
    cal::NOEVENTS,
    cal::USEOM,
    cal::USEOM2,
    cal::USMACRO,
    cal::TESTING,
    cal::OCCAM,
    cal::OCCAMZNUB,
    cal::OCCAMZN,
    cal::OCCAMEOD,
    cal::OCCAMEQ,
    cal::ALLEVENTS,
    cal::USEQOPEN,
    cal::USEQCLOSE,
    cal::USDAY,
}};

using cal_pair = std::pair<cal, const char*>;

inline constexpr std::array<cal_pair, 15> cal_name_hash = {{
    cal_pair{cal::NOEVENTS, "NOEVENTS"},
    cal_pair{cal::USEOM, "USEOM"},
    cal_pair{cal::USEOM2, "USEOM2"},
    cal_pair{cal::USMACRO, "USMACRO"},
    cal_pair{cal::TESTING, "TESTING"},
    cal_pair{cal::OCCAM, "OCCAM"},
    cal_pair{cal::OCCAMZNUB, "OCCAMZNUB"},
    cal_pair{cal::OCCAMZN, "OCCAMZN"},
    cal_pair{cal::OCCAMEOD, "OCCAMEOD"},
    cal_pair{cal::OCCAMEQ, "OCCAMEQ"},
    cal_pair{cal::ALLEVENTS, "ALLEVENTS"},
    cal_pair{cal::USEQOPEN, "USEQOPEN"},
    cal_pair{cal::USEQCLOSE, "USEQCLOSE"},
    cal_pair{cal::USDAY, "USDAY"},
    cal_pair{cal::UNI, "UNI"},
}};

// Type-safe array indexed by cal
template<typename T>
struct cal_array {
    std::array<T, 15> data;

    // Access operators
    constexpr T& operator[](cal idx) { return data[idx.value]; }
    constexpr const T& operator[](cal idx) const { return data[idx.value]; }

    constexpr T& at(cal idx) {
        if (idx.value >= data.size()) throw std::out_of_range("cal_array::at");
        return data[idx.value];
    }
    constexpr const T& at(cal idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("cal_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for cal

INLINE constexpr const char* to_string(cal n) {
    if (static_cast<std::size_t>(n.value) < cal_names.size()) {
        return cal_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t cal_num_syms() {
    return 15;
}

INLINE constexpr bool is_valid(cal n) {
    return (n.value < cal_num_syms() && n.value != cal::UNI);
}

INLINE bool cal_is_valid(std::string_view nam) {
    return std::find(cal_names.begin(), cal_names.end(), nam) != cal_names.end();
}

INLINE cal cal_index_of(std::string_view str) {
    auto it = std::find(cal_names.begin(), cal_names.end(), str);
    if (it == cal_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return cal(static_cast<std::uint32_t>(it - cal_names.begin()));
}

INLINE std::optional<cal> cal_try_parse(std::string_view str) {
    auto it = std::find(cal_names.begin(), cal_names.end(), str);
    if (it == cal_names.end()) {
        return std::nullopt;
    }
    return cal(static_cast<std::uint32_t>(it - cal_names.begin()));
}

struct cal_hash_t {
    bool contains(std::string_view key) const {
        return std::find(cal_names.begin(), cal_names.end(), key) != cal_names.end();
    }
    cal operator[](std::string_view key) const {
        return cal_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(cal_names.begin(), cal_names.end(), key);
        if (it != cal_names.end()) {
            return cal_name_hash.begin() + (it - cal_names.begin());
        }
        return cal_name_hash.end();
    }
    auto end() const { return cal_name_hash.end(); }
};
inline const cal_hash_t cal_hash;

// Operators for cal

INLINE std::ostream& operator<<(std::ostream& out, const cal& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::cal> {
        std::size_t operator()(en::cal e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
