// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify enums, edit the corresponding .enum files in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once

#include "chutil/Macros.hpp"

#include "enum/alpha.hpp"
#include "enum/buy_sell.hpp"
#include "enum/cal.hpp"
#include "enum/exch_code.hpp"
#include "enum/interval.hpp"
#include "enum/l3.hpp"
#include "enum/light_ev.hpp"
#include "enum/mat.hpp"
#include "enum/mod_typ.hpp"
#include "enum/models.hpp"
#include "enum/msg_code.hpp"
#include "enum/order_type.hpp"
#include "enum/pos.hpp"
#include "enum/rv_freq.hpp"
#include "enum/som_code.hpp"
#include "enum/th.hpp"
#include "enum/trader.hpp"
