// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct x {
    std::uint32_t value;
    enum {
        UNI,
        CMEMD,
        CMEILINK1,
        CMEILINK2,
        BTEC____,
        FENICS,
        DEALERWEB,
        DWAS,
        LE,
        FENICSOTR,
        FENICSPREMIUM,
        CMEMDFUT,
        FENICSGLOBAL,
        DWAS2,
        FENICSSTREAM1,
        FENICSSTREAM2,
        LE_ODDLOT,
        LE_OLDS,
        SIM,
        FENICSTAKER,
        DWAS3,
        DWAS4,
        FENICSFILTERED,
        STATS,
        FENICSDVRV
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr x() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr x(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for x
inline constexpr std::array<const char*, 25> x_names = {{
    "UNI",
    "CMEMD",
    "CMEILINK1",
    "CMEILINK2",
    "BTEC____",
    "FENICS",
    "DEALERWEB",
    "DWAS",
    "LE",
    "FENICSOTR",
    "FENICSPREMIUM",
    "CMEMDFUT",
    "FENICSGLOBAL",
    "DWAS2",
    "FENICSSTREAM1",
    "FENICSSTREAM2",
    "LE_ODDLOT",
    "LE_OLDS",
    "SIM",
    "FENICSTAKER",
    "DWAS3",
    "DWAS4",
    "FENICSFILTERED",
    "STATS",
    "FENICSDVRV",
}};

inline constexpr std::array<std::uint32_t, 25> x_values = {{
    x::UNI,
    x::CMEMD,
    x::CMEILINK1,
    x::CMEILINK2,
    x::BTEC____,
    x::FENICS,
    x::DEALERWEB,
    x::DWAS,
    x::LE,
    x::FENICSOTR,
    x::FENICSPREMIUM,
    x::CMEMDFUT,
    x::FENICSGLOBAL,
    x::DWAS2,
    x::FENICSSTREAM1,
    x::FENICSSTREAM2,
    x::LE_ODDLOT,
    x::LE_OLDS,
    x::SIM,
    x::FENICSTAKER,
    x::DWAS3,
    x::DWAS4,
    x::FENICSFILTERED,
    x::STATS,
    x::FENICSDVRV,
}};

using x_pair = std::pair<x, const char*>;

inline constexpr std::array<x_pair, 25> x_name_hash = {{
    x_pair{x::UNI, "UNI"},
    x_pair{x::CMEMD, "CMEMD"},
    x_pair{x::CMEILINK1, "CMEILINK1"},
    x_pair{x::CMEILINK2, "CMEILINK2"},
    x_pair{x::BTEC____, "BTEC____"},
    x_pair{x::FENICS, "FENICS"},
    x_pair{x::DEALERWEB, "DEALERWEB"},
    x_pair{x::DWAS, "DWAS"},
    x_pair{x::LE, "LE"},
    x_pair{x::FENICSOTR, "FENICSOTR"},
    x_pair{x::FENICSPREMIUM, "FENICSPREMIUM"},
    x_pair{x::CMEMDFUT, "CMEMDFUT"},
    x_pair{x::FENICSGLOBAL, "FENICSGLOBAL"},
    x_pair{x::DWAS2, "DWAS2"},
    x_pair{x::FENICSSTREAM1, "FENICSSTREAM1"},
    x_pair{x::FENICSSTREAM2, "FENICSSTREAM2"},
    x_pair{x::LE_ODDLOT, "LE_ODDLOT"},
    x_pair{x::LE_OLDS, "LE_OLDS"},
    x_pair{x::SIM, "SIM"},
    x_pair{x::FENICSTAKER, "FENICSTAKER"},
    x_pair{x::DWAS3, "DWAS3"},
    x_pair{x::DWAS4, "DWAS4"},
    x_pair{x::FENICSFILTERED, "FENICSFILTERED"},
    x_pair{x::STATS, "STATS"},
    x_pair{x::FENICSDVRV, "FENICSDVRV"},
}};

// Type-safe array indexed by x
template<typename T>
struct x_array {
    std::array<T, 25> data;

    // Access operators
    constexpr T& operator[](x idx) { return data[idx.value]; }
    constexpr const T& operator[](x idx) const { return data[idx.value]; }

    constexpr T& at(x idx) {
        if (idx.value >= data.size()) throw std::out_of_range("x_array::at");
        return data[idx.value];
    }
    constexpr const T& at(x idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("x_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for x

INLINE constexpr const char* to_string(x n) {
    if (static_cast<std::size_t>(n.value) < x_names.size()) {
        return x_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t x_num_syms() {
    return 25;
}

INLINE constexpr bool is_valid(x n) {
    return (n.value < x_num_syms() && n.value != x::UNI);
}

INLINE bool x_is_valid(std::string_view nam) {
    return std::find(x_names.begin(), x_names.end(), nam) != x_names.end();
}

INLINE x x_index_of(std::string_view str) {
    auto it = std::find(x_names.begin(), x_names.end(), str);
    if (it == x_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return x(static_cast<std::uint32_t>(it - x_names.begin()));
}

INLINE std::optional<x> x_try_parse(std::string_view str) {
    auto it = std::find(x_names.begin(), x_names.end(), str);
    if (it == x_names.end()) {
        return std::nullopt;
    }
    return x(static_cast<std::uint32_t>(it - x_names.begin()));
}

struct x_hash_t {
    bool contains(std::string_view key) const {
        return std::find(x_names.begin(), x_names.end(), key) != x_names.end();
    }
    x operator[](std::string_view key) const {
        return x_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(x_names.begin(), x_names.end(), key);
        if (it != x_names.end()) {
            return x_name_hash.begin() + (it - x_names.begin());
        }
        return x_name_hash.end();
    }
    auto end() const { return x_name_hash.end(); }
};
inline const x_hash_t x_hash;

// Operators for x

INLINE std::ostream& operator<<(std::ostream& out, const x& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::x> {
        std::size_t operator()(en::x e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
