// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct intreval {
    std::uint32_t value;
    enum {
        UNI,
        AGGR_EOB,
        OB_DATA_HANDLER_EOB,
        OB_DATA_HANDLER_TRADE,
        LIGHT_EOB,
        SOM_ORDER,
        SOM_CANCEL,
        LE_OM
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr intreval() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr intreval(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for intreval
inline constexpr std::array<const char*, 8> intreval_names = {{
    "UNI",
    "AGGR_EOB",
    "OB_DATA_HANDLER_EOB",
    "OB_DATA_HANDLER_TRADE",
    "LIGHT_EOB",
    "SOM_ORDER",
    "SOM_CANCEL",
    "LE_OM",
}};

inline constexpr std::array<std::uint32_t, 8> intreval_values = {{
    intreval::UNI,
    intreval::AGGR_EOB,
    intreval::OB_DATA_HANDLER_EOB,
    intreval::OB_DATA_HANDLER_TRADE,
    intreval::LIGHT_EOB,
    intreval::SOM_ORDER,
    intreval::SOM_CANCEL,
    intreval::LE_OM,
}};

using intreval_pair = std::pair<intreval, const char*>;

inline constexpr std::array<intreval_pair, 8> intreval_name_hash = {{
    intreval_pair{intreval::UNI, "UNI"},
    intreval_pair{intreval::AGGR_EOB, "AGGR_EOB"},
    intreval_pair{intreval::OB_DATA_HANDLER_EOB, "OB_DATA_HANDLER_EOB"},
    intreval_pair{intreval::OB_DATA_HANDLER_TRADE, "OB_DATA_HANDLER_TRADE"},
    intreval_pair{intreval::LIGHT_EOB, "LIGHT_EOB"},
    intreval_pair{intreval::SOM_ORDER, "SOM_ORDER"},
    intreval_pair{intreval::SOM_CANCEL, "SOM_CANCEL"},
    intreval_pair{intreval::LE_OM, "LE_OM"},
}};

// Type-safe array indexed by intreval
template<typename T>
struct intreval_array {
    std::array<T, 8> data;

    // Access operators
    constexpr T& operator[](intreval idx) { return data[idx.value]; }
    constexpr const T& operator[](intreval idx) const { return data[idx.value]; }

    constexpr T& at(intreval idx) {
        if (idx.value >= data.size()) throw std::out_of_range("intreval_array::at");
        return data[idx.value];
    }
    constexpr const T& at(intreval idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("intreval_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for intreval

INLINE constexpr const char* to_string(intreval n) {
    if (static_cast<std::size_t>(n.value) < intreval_names.size()) {
        return intreval_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t intreval_num_syms() {
    return 8;
}

INLINE constexpr bool is_valid(intreval n) {
    return (n.value < intreval_num_syms() && n.value != intreval::UNI);
}

INLINE bool intreval_is_valid(std::string_view nam) {
    return std::find(intreval_names.begin(), intreval_names.end(), nam) != intreval_names.end();
}

INLINE intreval intreval_index_of(std::string_view str) {
    auto it = std::find(intreval_names.begin(), intreval_names.end(), str);
    if (it == intreval_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return intreval(static_cast<std::uint32_t>(it - intreval_names.begin()));
}

INLINE std::optional<intreval> intreval_try_parse(std::string_view str) {
    auto it = std::find(intreval_names.begin(), intreval_names.end(), str);
    if (it == intreval_names.end()) {
        return std::nullopt;
    }
    return intreval(static_cast<std::uint32_t>(it - intreval_names.begin()));
}

struct intreval_hash_t {
    bool contains(std::string_view key) const {
        return std::find(intreval_names.begin(), intreval_names.end(), key) != intreval_names.end();
    }
    intreval operator[](std::string_view key) const {
        return intreval_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(intreval_names.begin(), intreval_names.end(), key);
        if (it != intreval_names.end()) {
            return intreval_name_hash.begin() + (it - intreval_names.begin());
        }
        return intreval_name_hash.end();
    }
    auto end() const { return intreval_name_hash.end(); }
};
inline const intreval_hash_t intreval_hash;

// Operators for intreval

INLINE std::ostream& operator<<(std::ostream& out, const intreval& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::intreval> {
        std::size_t operator()(en::intreval e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
