// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct l3 {
    std::uint32_t value;
    enum {
        UNI,
        MBO_V1,
        MBOT_V1,
        MBP,
        MBPT,
        SOM,
        VOL,
        SST,
        FDF,
        ODF,
        SDF,
        LIM,
        CHR_V1,
        GAP_V1,
        EOB,
        MBOS,
        MBO_V2,
        CHR_V2,
        GAP_V2,
        MBOT_V2,
        FENICS_SYSTEMEVENT,
        FENICS_INSTRUMENTTRADINGACTION,
        FENICS_INSTRUMENTSTATS,
        FENICS_BDF,
        DEALERWEB_BOOKDIR,
        DEALERWEB_SYSEVENT,
        DEALERWEB_ORDERBOOKSTATE,
        DEALERWEB_INFORMATION,
        DEALERWEB_BROKENTRADE,
        INTERVAL,
        QLEN,
        VOLUME
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr l3() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr l3(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for l3
inline constexpr std::array<const char*, 32> l3_names = {{
    "UNI",
    "MBO_V1",
    "MBOT_V1",
    "MBP",
    "MBPT",
    "SOM",
    "VOL",
    "SST",
    "FDF",
    "ODF",
    "SDF",
    "LIM",
    "CHR_V1",
    "GAP_V1",
    "EOB",
    "MBOS",
    "MBO_V2",
    "CHR_V2",
    "GAP_V2",
    "MBOT_V2",
    "FENICS_SYSTEMEVENT",
    "FENICS_INSTRUMENTTRADINGACTION",
    "FENICS_INSTRUMENTSTATS",
    "FENICS_BDF",
    "DEALERWEB_BOOKDIR",
    "DEALERWEB_SYSEVENT",
    "DEALERWEB_ORDERBOOKSTATE",
    "DEALERWEB_INFORMATION",
    "DEALERWEB_BROKENTRADE",
    "INTERVAL",
    "QLEN",
    "VOLUME",
}};

inline constexpr std::array<std::uint32_t, 32> l3_values = {{
    l3::UNI,
    l3::MBO_V1,
    l3::MBOT_V1,
    l3::MBP,
    l3::MBPT,
    l3::SOM,
    l3::VOL,
    l3::SST,
    l3::FDF,
    l3::ODF,
    l3::SDF,
    l3::LIM,
    l3::CHR_V1,
    l3::GAP_V1,
    l3::EOB,
    l3::MBOS,
    l3::MBO_V2,
    l3::CHR_V2,
    l3::GAP_V2,
    l3::MBOT_V2,
    l3::FENICS_SYSTEMEVENT,
    l3::FENICS_INSTRUMENTTRADINGACTION,
    l3::FENICS_INSTRUMENTSTATS,
    l3::FENICS_BDF,
    l3::DEALERWEB_BOOKDIR,
    l3::DEALERWEB_SYSEVENT,
    l3::DEALERWEB_ORDERBOOKSTATE,
    l3::DEALERWEB_INFORMATION,
    l3::DEALERWEB_BROKENTRADE,
    l3::INTERVAL,
    l3::QLEN,
    l3::VOLUME,
}};

using l3_pair = std::pair<l3, const char*>;

inline constexpr std::array<l3_pair, 32> l3_name_hash = {{
    l3_pair{l3::UNI, "UNI"},
    l3_pair{l3::MBO_V1, "MBO_V1"},
    l3_pair{l3::MBOT_V1, "MBOT_V1"},
    l3_pair{l3::MBP, "MBP"},
    l3_pair{l3::MBPT, "MBPT"},
    l3_pair{l3::SOM, "SOM"},
    l3_pair{l3::VOL, "VOL"},
    l3_pair{l3::SST, "SST"},
    l3_pair{l3::FDF, "FDF"},
    l3_pair{l3::ODF, "ODF"},
    l3_pair{l3::SDF, "SDF"},
    l3_pair{l3::LIM, "LIM"},
    l3_pair{l3::CHR_V1, "CHR_V1"},
    l3_pair{l3::GAP_V1, "GAP_V1"},
    l3_pair{l3::EOB, "EOB"},
    l3_pair{l3::MBOS, "MBOS"},
    l3_pair{l3::MBO_V2, "MBO_V2"},
    l3_pair{l3::CHR_V2, "CHR_V2"},
    l3_pair{l3::GAP_V2, "GAP_V2"},
    l3_pair{l3::MBOT_V2, "MBOT_V2"},
    l3_pair{l3::FENICS_SYSTEMEVENT, "FENICS_SYSTEMEVENT"},
    l3_pair{l3::FENICS_INSTRUMENTTRADINGACTION, "FENICS_INSTRUMENTTRADINGACTION"},
    l3_pair{l3::FENICS_INSTRUMENTSTATS, "FENICS_INSTRUMENTSTATS"},
    l3_pair{l3::FENICS_BDF, "FENICS_BDF"},
    l3_pair{l3::DEALERWEB_BOOKDIR, "DEALERWEB_BOOKDIR"},
    l3_pair{l3::DEALERWEB_SYSEVENT, "DEALERWEB_SYSEVENT"},
    l3_pair{l3::DEALERWEB_ORDERBOOKSTATE, "DEALERWEB_ORDERBOOKSTATE"},
    l3_pair{l3::DEALERWEB_INFORMATION, "DEALERWEB_INFORMATION"},
    l3_pair{l3::DEALERWEB_BROKENTRADE, "DEALERWEB_BROKENTRADE"},
    l3_pair{l3::INTERVAL, "INTERVAL"},
    l3_pair{l3::QLEN, "QLEN"},
    l3_pair{l3::VOLUME, "VOLUME"},
}};

// Type-safe array indexed by l3
template<typename T>
struct l3_array {
    std::array<T, 32> data;

    // Access operators
    constexpr T& operator[](l3 idx) { return data[idx.value]; }
    constexpr const T& operator[](l3 idx) const { return data[idx.value]; }

    constexpr T& at(l3 idx) {
        if (idx.value >= data.size()) throw std::out_of_range("l3_array::at");
        return data[idx.value];
    }
    constexpr const T& at(l3 idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("l3_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for l3

INLINE constexpr const char* to_string(l3 n) {
    if (static_cast<std::size_t>(n.value) < l3_names.size()) {
        return l3_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t l3_num_syms() {
    return 32;
}

INLINE constexpr bool is_valid(l3 n) {
    return (n.value < l3_num_syms() && n.value != l3::UNI);
}

INLINE bool l3_is_valid(std::string_view nam) {
    return std::find(l3_names.begin(), l3_names.end(), nam) != l3_names.end();
}

INLINE l3 l3_index_of(std::string_view str) {
    auto it = std::find(l3_names.begin(), l3_names.end(), str);
    if (it == l3_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return l3(static_cast<std::uint32_t>(it - l3_names.begin()));
}

INLINE std::optional<l3> l3_try_parse(std::string_view str) {
    auto it = std::find(l3_names.begin(), l3_names.end(), str);
    if (it == l3_names.end()) {
        return std::nullopt;
    }
    return l3(static_cast<std::uint32_t>(it - l3_names.begin()));
}

struct l3_hash_t {
    bool contains(std::string_view key) const {
        return std::find(l3_names.begin(), l3_names.end(), key) != l3_names.end();
    }
    l3 operator[](std::string_view key) const {
        return l3_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(l3_names.begin(), l3_names.end(), key);
        if (it != l3_names.end()) {
            return l3_name_hash.begin() + (it - l3_names.begin());
        }
        return l3_name_hash.end();
    }
    auto end() const { return l3_name_hash.end(); }
};
inline const l3_hash_t l3_hash;

// Operators for l3

INLINE std::ostream& operator<<(std::ostream& out, const l3& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::l3> {
        std::size_t operator()(en::l3 e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
