// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct lightev {
    std::uint32_t value;
    enum {
        STOP,
        START,
        START_SHORT,
        START_LONG,
        SHORT_ONLY,
        LONG_ONLY,
        SET1,
        SET2,
        SET3,
        STARTVOLTRACK,
        STOPVOLTRACK,
        HEDGE_ON,
        HEDGE_OFF,
        UNI
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr lightev() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr lightev(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for lightev
inline constexpr std::array<const char*, 14> lightev_names = {{
    "STOP",
    "START",
    "START_SHORT",
    "START_LONG",
    "SHORT_ONLY",
    "LONG_ONLY",
    "SET1",
    "SET2",
    "SET3",
    "STARTVOLTRACK",
    "STOPVOLTRACK",
    "HEDGE_ON",
    "HEDGE_OFF",
    "UNI",
}};

inline constexpr std::array<std::uint32_t, 14> lightev_values = {{
    lightev::STOP,
    lightev::START,
    lightev::START_SHORT,
    lightev::START_LONG,
    lightev::SHORT_ONLY,
    lightev::LONG_ONLY,
    lightev::SET1,
    lightev::SET2,
    lightev::SET3,
    lightev::STARTVOLTRACK,
    lightev::STOPVOLTRACK,
    lightev::HEDGE_ON,
    lightev::HEDGE_OFF,
    lightev::UNI,
}};

inline constexpr std::array<std::uint32_t, 13> lightev_all = {{
    lightev::STOP,
    lightev::START,
    lightev::START_SHORT,
    lightev::START_LONG,
    lightev::SHORT_ONLY,
    lightev::LONG_ONLY,
    lightev::SET1,
    lightev::SET2,
    lightev::SET3,
    lightev::STARTVOLTRACK,
    lightev::STOPVOLTRACK,
    lightev::HEDGE_ON,
    lightev::HEDGE_OFF,
}};

using lightev_pair = std::pair<lightev, const char*>;

inline constexpr std::array<lightev_pair, 14> lightev_name_hash = {{
    lightev_pair{lightev::STOP, "STOP"},
    lightev_pair{lightev::START, "START"},
    lightev_pair{lightev::START_SHORT, "START_SHORT"},
    lightev_pair{lightev::START_LONG, "START_LONG"},
    lightev_pair{lightev::SHORT_ONLY, "SHORT_ONLY"},
    lightev_pair{lightev::LONG_ONLY, "LONG_ONLY"},
    lightev_pair{lightev::SET1, "SET1"},
    lightev_pair{lightev::SET2, "SET2"},
    lightev_pair{lightev::SET3, "SET3"},
    lightev_pair{lightev::STARTVOLTRACK, "STARTVOLTRACK"},
    lightev_pair{lightev::STOPVOLTRACK, "STOPVOLTRACK"},
    lightev_pair{lightev::HEDGE_ON, "HEDGE_ON"},
    lightev_pair{lightev::HEDGE_OFF, "HEDGE_OFF"},
    lightev_pair{lightev::UNI, "UNI"},
}};

// Type-safe array indexed by lightev
template<typename T>
struct lightev_array {
    std::array<T, 14> data;

    // Access operators
    constexpr T& operator[](lightev idx) { return data[idx.value]; }
    constexpr const T& operator[](lightev idx) const { return data[idx.value]; }

    constexpr T& at(lightev idx) {
        if (idx.value >= data.size()) throw std::out_of_range("lightev_array::at");
        return data[idx.value];
    }
    constexpr const T& at(lightev idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("lightev_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for lightev

INLINE constexpr const char* to_string(lightev n) {
    if (static_cast<std::size_t>(n.value) < lightev_names.size()) {
        return lightev_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t lightev_num_syms() {
    return 14;
}

INLINE constexpr bool is_valid(lightev n) {
    return (n.value < lightev_num_syms() && n.value != lightev::UNI);
}

INLINE bool lightev_is_valid(std::string_view nam) {
    return std::find(lightev_names.begin(), lightev_names.end(), nam) != lightev_names.end();
}

INLINE lightev lightev_index_of(std::string_view str) {
    auto it = std::find(lightev_names.begin(), lightev_names.end(), str);
    if (it == lightev_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return lightev(static_cast<std::uint32_t>(it - lightev_names.begin()));
}

INLINE std::optional<lightev> lightev_try_parse(std::string_view str) {
    auto it = std::find(lightev_names.begin(), lightev_names.end(), str);
    if (it == lightev_names.end()) {
        return std::nullopt;
    }
    return lightev(static_cast<std::uint32_t>(it - lightev_names.begin()));
}

struct lightev_hash_t {
    bool contains(std::string_view key) const {
        return std::find(lightev_names.begin(), lightev_names.end(), key) != lightev_names.end();
    }
    lightev operator[](std::string_view key) const {
        return lightev_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(lightev_names.begin(), lightev_names.end(), key);
        if (it != lightev_names.end()) {
            return lightev_name_hash.begin() + (it - lightev_names.begin());
        }
        return lightev_name_hash.end();
    }
    auto end() const { return lightev_name_hash.end(); }
};
inline const lightev_hash_t lightev_hash;

// Operators for lightev

INLINE std::ostream& operator<<(std::ostream& out, const lightev& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::lightev> {
        std::size_t operator()(en::lightev e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
