// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct mat {
    std::uint32_t value;
    enum {
        UNI,
        _2Y,
        _3Y,
        _5Y,
        _7Y,
        _10Y,
        _20Y,
        _30Y
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr mat() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr mat(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for mat
inline constexpr std::array<const char*, 8> mat_names = {{
    "UNI",
    "2Y",
    "3Y",
    "5Y",
    "7Y",
    "10Y",
    "20Y",
    "30Y",
}};

inline constexpr std::array<std::uint32_t, 8> mat_values = {{
    mat::UNI,
    mat::_2Y,
    mat::_3Y,
    mat::_5Y,
    mat::_7Y,
    mat::_10Y,
    mat::_20Y,
    mat::_30Y,
}};

using mat_pair = std::pair<mat, const char*>;

inline constexpr std::array<mat_pair, 8> mat_name_hash = {{
    mat_pair{mat::UNI, "UNI"},
    mat_pair{mat::_2Y, "2Y"},
    mat_pair{mat::_3Y, "3Y"},
    mat_pair{mat::_5Y, "5Y"},
    mat_pair{mat::_7Y, "7Y"},
    mat_pair{mat::_10Y, "10Y"},
    mat_pair{mat::_20Y, "20Y"},
    mat_pair{mat::_30Y, "30Y"},
}};

// Type-safe array indexed by mat
template<typename T>
struct mat_array {
    std::array<T, 8> data;

    // Access operators
    constexpr T& operator[](mat idx) { return data[idx.value]; }
    constexpr const T& operator[](mat idx) const { return data[idx.value]; }

    constexpr T& at(mat idx) {
        if (idx.value >= data.size()) throw std::out_of_range("mat_array::at");
        return data[idx.value];
    }
    constexpr const T& at(mat idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("mat_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for mat

INLINE constexpr const char* to_string(mat n) {
    if (static_cast<std::size_t>(n.value) < mat_names.size()) {
        return mat_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t mat_num_syms() {
    return 8;
}

INLINE constexpr bool is_valid(mat n) {
    return (n.value < mat_num_syms() && n.value != mat::UNI);
}

INLINE bool mat_is_valid(std::string_view nam) {
    return std::find(mat_names.begin(), mat_names.end(), nam) != mat_names.end();
}

INLINE mat mat_index_of(std::string_view str) {
    auto it = std::find(mat_names.begin(), mat_names.end(), str);
    if (it == mat_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return mat(static_cast<std::uint32_t>(it - mat_names.begin()));
}

INLINE std::optional<mat> mat_try_parse(std::string_view str) {
    auto it = std::find(mat_names.begin(), mat_names.end(), str);
    if (it == mat_names.end()) {
        return std::nullopt;
    }
    return mat(static_cast<std::uint32_t>(it - mat_names.begin()));
}

struct mat_hash_t {
    bool contains(std::string_view key) const {
        return std::find(mat_names.begin(), mat_names.end(), key) != mat_names.end();
    }
    mat operator[](std::string_view key) const {
        return mat_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(mat_names.begin(), mat_names.end(), key);
        if (it != mat_names.end()) {
            return mat_name_hash.begin() + (it - mat_names.begin());
        }
        return mat_name_hash.end();
    }
    auto end() const { return mat_name_hash.end(); }
};
inline const mat_hash_t mat_hash;

// Operators for mat

INLINE std::ostream& operator<<(std::ostream& out, const mat& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::mat> {
        std::size_t operator()(en::mat e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
