// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct mt {
    std::uint32_t value;
    enum {
        EXEC,
        CANC,
        NONE,
        UNI,
        CANCD,
        EXECD
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr mt() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr mt(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for mt
inline constexpr std::array<const char*, 6> mt_names = {{
    "EXEC",
    "CANC",
    "NONE",
    "UNI",
    "CANCD",
    "EXECD",
}};

inline constexpr std::array<std::uint32_t, 6> mt_values = {{
    mt::EXEC,
    mt::CANC,
    mt::NONE,
    mt::UNI,
    mt::CANCD,
    mt::EXECD,
}};

inline constexpr std::array<std::uint32_t, 3> mt_all = {{
    mt::EXEC,
    mt::CANC,
    mt::NONE,
}};

using mt_pair = std::pair<mt, const char*>;

inline constexpr std::array<mt_pair, 6> mt_name_hash = {{
    mt_pair{mt::EXEC, "EXEC"},
    mt_pair{mt::CANC, "CANC"},
    mt_pair{mt::NONE, "NONE"},
    mt_pair{mt::UNI, "UNI"},
    mt_pair{mt::CANCD, "CANCD"},
    mt_pair{mt::EXECD, "EXECD"},
}};

// Type-safe array indexed by mt
template<typename T>
struct mt_array {
    std::array<T, 6> data;

    // Access operators
    constexpr T& operator[](mt idx) { return data[idx.value]; }
    constexpr const T& operator[](mt idx) const { return data[idx.value]; }

    constexpr T& at(mt idx) {
        if (idx.value >= data.size()) throw std::out_of_range("mt_array::at");
        return data[idx.value];
    }
    constexpr const T& at(mt idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("mt_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for mt

INLINE constexpr const char* to_string(mt n) {
    if (static_cast<std::size_t>(n.value) < mt_names.size()) {
        return mt_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t mt_num_syms() {
    return 6;
}

INLINE constexpr bool is_valid(mt n) {
    return (n.value < mt_num_syms() && n.value != mt::UNI);
}

INLINE bool mt_is_valid(std::string_view nam) {
    return std::find(mt_names.begin(), mt_names.end(), nam) != mt_names.end();
}

INLINE mt mt_index_of(std::string_view str) {
    auto it = std::find(mt_names.begin(), mt_names.end(), str);
    if (it == mt_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return mt(static_cast<std::uint32_t>(it - mt_names.begin()));
}

INLINE std::optional<mt> mt_try_parse(std::string_view str) {
    auto it = std::find(mt_names.begin(), mt_names.end(), str);
    if (it == mt_names.end()) {
        return std::nullopt;
    }
    return mt(static_cast<std::uint32_t>(it - mt_names.begin()));
}

struct mt_hash_t {
    bool contains(std::string_view key) const {
        return std::find(mt_names.begin(), mt_names.end(), key) != mt_names.end();
    }
    mt operator[](std::string_view key) const {
        return mt_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(mt_names.begin(), mt_names.end(), key);
        if (it != mt_names.end()) {
            return mt_name_hash.begin() + (it - mt_names.begin());
        }
        return mt_name_hash.end();
    }
    auto end() const { return mt_name_hash.end(); }
};
inline const mt_hash_t mt_hash;

// Operators for mt

INLINE std::ostream& operator<<(std::ostream& out, const mt& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::mt> {
        std::size_t operator()(en::mt e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
