// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct models {
    std::uint32_t value;
    enum {
        UNI,
        level0vwap,
        level1vwap,
        level2vwap,
        level3vwap,
        level4vwap,
        level5vwap,
        level6vwap
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr models() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr models(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for models
inline constexpr std::array<const char*, 8> models_names = {{
    "UNI",
    "level0vwap",
    "level1vwap",
    "level2vwap",
    "level3vwap",
    "level4vwap",
    "level5vwap",
    "level6vwap",
}};

inline constexpr std::array<std::uint32_t, 8> models_values = {{
    models::UNI,
    models::level0vwap,
    models::level1vwap,
    models::level2vwap,
    models::level3vwap,
    models::level4vwap,
    models::level5vwap,
    models::level6vwap,
}};

using models_pair = std::pair<models, const char*>;

inline constexpr std::array<models_pair, 8> models_name_hash = {{
    models_pair{models::UNI, "UNI"},
    models_pair{models::level0vwap, "level0vwap"},
    models_pair{models::level1vwap, "level1vwap"},
    models_pair{models::level2vwap, "level2vwap"},
    models_pair{models::level3vwap, "level3vwap"},
    models_pair{models::level4vwap, "level4vwap"},
    models_pair{models::level5vwap, "level5vwap"},
    models_pair{models::level6vwap, "level6vwap"},
}};

// Type-safe array indexed by models
template<typename T>
struct models_array {
    std::array<T, 8> data;

    // Access operators
    constexpr T& operator[](models idx) { return data[idx.value]; }
    constexpr const T& operator[](models idx) const { return data[idx.value]; }

    constexpr T& at(models idx) {
        if (idx.value >= data.size()) throw std::out_of_range("models_array::at");
        return data[idx.value];
    }
    constexpr const T& at(models idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("models_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for models

INLINE constexpr const char* to_string(models n) {
    if (static_cast<std::size_t>(n.value) < models_names.size()) {
        return models_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t models_num_syms() {
    return 8;
}

INLINE constexpr bool is_valid(models n) {
    return (n.value < models_num_syms() && n.value != models::UNI);
}

INLINE bool models_is_valid(std::string_view nam) {
    return std::find(models_names.begin(), models_names.end(), nam) != models_names.end();
}

INLINE models models_index_of(std::string_view str) {
    auto it = std::find(models_names.begin(), models_names.end(), str);
    if (it == models_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return models(static_cast<std::uint32_t>(it - models_names.begin()));
}

INLINE std::optional<models> models_try_parse(std::string_view str) {
    auto it = std::find(models_names.begin(), models_names.end(), str);
    if (it == models_names.end()) {
        return std::nullopt;
    }
    return models(static_cast<std::uint32_t>(it - models_names.begin()));
}

struct models_hash_t {
    bool contains(std::string_view key) const {
        return std::find(models_names.begin(), models_names.end(), key) != models_names.end();
    }
    models operator[](std::string_view key) const {
        return models_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(models_names.begin(), models_names.end(), key);
        if (it != models_names.end()) {
            return models_name_hash.begin() + (it - models_names.begin());
        }
        return models_name_hash.end();
    }
    auto end() const { return models_name_hash.end(); }
};
inline const models_hash_t models_hash;

// Operators for models

INLINE std::ostream& operator<<(std::ostream& out, const models& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::models> {
        std::size_t operator()(en::models e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
