// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct md {
    std::uint32_t value;
    enum {
        ADD,
        MOD,
        DEL,
        UNI,
        EXEC,
        EOE,
        CLEAR,
        TEST,
        EOP,
        GAP,
        EOBURST
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr md() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr md(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for md
inline constexpr std::array<const char*, 11> md_names = {{
    "ADD",
    "MOD",
    "DEL",
    "UNI",
    "EXEC",
    "EOE",
    "CLEAR",
    "TEST",
    "EOP",
    "GAP",
    "EOBURST",
}};

inline constexpr std::array<std::uint32_t, 11> md_values = {{
    md::ADD,
    md::MOD,
    md::DEL,
    md::UNI,
    md::EXEC,
    md::EOE,
    md::CLEAR,
    md::TEST,
    md::EOP,
    md::GAP,
    md::EOBURST,
}};

inline constexpr std::array<std::uint32_t, 3> md_all = {{
    md::ADD,
    md::MOD,
    md::DEL,
}};

using md_pair = std::pair<md, const char*>;

inline constexpr std::array<md_pair, 11> md_name_hash = {{
    md_pair{md::ADD, "ADD"},
    md_pair{md::MOD, "MOD"},
    md_pair{md::DEL, "DEL"},
    md_pair{md::UNI, "UNI"},
    md_pair{md::EXEC, "EXEC"},
    md_pair{md::EOE, "EOE"},
    md_pair{md::CLEAR, "CLEAR"},
    md_pair{md::TEST, "TEST"},
    md_pair{md::EOP, "EOP"},
    md_pair{md::GAP, "GAP"},
    md_pair{md::EOBURST, "EOBURST"},
}};

// Type-safe array indexed by md
template<typename T>
struct md_array {
    std::array<T, 11> data;

    // Access operators
    constexpr T& operator[](md idx) { return data[idx.value]; }
    constexpr const T& operator[](md idx) const { return data[idx.value]; }

    constexpr T& at(md idx) {
        if (idx.value >= data.size()) throw std::out_of_range("md_array::at");
        return data[idx.value];
    }
    constexpr const T& at(md idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("md_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for md

INLINE constexpr const char* to_string(md n) {
    if (static_cast<std::size_t>(n.value) < md_names.size()) {
        return md_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t md_num_syms() {
    return 11;
}

INLINE constexpr bool is_valid(md n) {
    return (n.value < md_num_syms() && n.value != md::UNI);
}

INLINE bool md_is_valid(std::string_view nam) {
    return std::find(md_names.begin(), md_names.end(), nam) != md_names.end();
}

INLINE md md_index_of(std::string_view str) {
    auto it = std::find(md_names.begin(), md_names.end(), str);
    if (it == md_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return md(static_cast<std::uint32_t>(it - md_names.begin()));
}

INLINE std::optional<md> md_try_parse(std::string_view str) {
    auto it = std::find(md_names.begin(), md_names.end(), str);
    if (it == md_names.end()) {
        return std::nullopt;
    }
    return md(static_cast<std::uint32_t>(it - md_names.begin()));
}

struct md_hash_t {
    bool contains(std::string_view key) const {
        return std::find(md_names.begin(), md_names.end(), key) != md_names.end();
    }
    md operator[](std::string_view key) const {
        return md_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(md_names.begin(), md_names.end(), key);
        if (it != md_names.end()) {
            return md_name_hash.begin() + (it - md_names.begin());
        }
        return md_name_hash.end();
    }
    auto end() const { return md_name_hash.end(); }
};
inline const md_hash_t md_hash;

// Operators for md

INLINE std::ostream& operator<<(std::ostream& out, const md& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::md> {
        std::size_t operator()(en::md e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
