// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct ot {
    std::uint32_t value;
    enum {
        LIMIT,
        UNI
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr ot() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr ot(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for ot
inline constexpr std::array<const char*, 2> ot_names = {{
    "LIMIT",
    "UNI",
}};

inline constexpr std::array<std::uint32_t, 2> ot_values = {{
    ot::LIMIT,
    ot::UNI,
}};

inline constexpr std::array<std::uint32_t, 1> ot_all = {{
    ot::LIMIT,
}};

using ot_pair = std::pair<ot, const char*>;

inline constexpr std::array<ot_pair, 2> ot_name_hash = {{
    ot_pair{ot::LIMIT, "LIMIT"},
    ot_pair{ot::UNI, "UNI"},
}};

// Type-safe array indexed by ot
template<typename T>
struct ot_array {
    std::array<T, 2> data;

    // Access operators
    constexpr T& operator[](ot idx) { return data[idx.value]; }
    constexpr const T& operator[](ot idx) const { return data[idx.value]; }

    constexpr T& at(ot idx) {
        if (idx.value >= data.size()) throw std::out_of_range("ot_array::at");
        return data[idx.value];
    }
    constexpr const T& at(ot idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("ot_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for ot

INLINE constexpr const char* to_string(ot n) {
    if (static_cast<std::size_t>(n.value) < ot_names.size()) {
        return ot_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t ot_num_syms() {
    return 2;
}

INLINE constexpr bool is_valid(ot n) {
    return (n.value < ot_num_syms() && n.value != ot::UNI);
}

INLINE bool ot_is_valid(std::string_view nam) {
    return std::find(ot_names.begin(), ot_names.end(), nam) != ot_names.end();
}

INLINE ot ot_index_of(std::string_view str) {
    auto it = std::find(ot_names.begin(), ot_names.end(), str);
    if (it == ot_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return ot(static_cast<std::uint32_t>(it - ot_names.begin()));
}

INLINE std::optional<ot> ot_try_parse(std::string_view str) {
    auto it = std::find(ot_names.begin(), ot_names.end(), str);
    if (it == ot_names.end()) {
        return std::nullopt;
    }
    return ot(static_cast<std::uint32_t>(it - ot_names.begin()));
}

struct ot_hash_t {
    bool contains(std::string_view key) const {
        return std::find(ot_names.begin(), ot_names.end(), key) != ot_names.end();
    }
    ot operator[](std::string_view key) const {
        return ot_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(ot_names.begin(), ot_names.end(), key);
        if (it != ot_names.end()) {
            return ot_name_hash.begin() + (it - ot_names.begin());
        }
        return ot_name_hash.end();
    }
    auto end() const { return ot_name_hash.end(); }
};
inline const ot_hash_t ot_hash;

// Operators for ot

INLINE std::ostream& operator<<(std::ostream& out, const ot& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::ot> {
        std::size_t operator()(en::ot e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
