// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct pos {
    std::uint32_t value;
    enum {
        LONG,
        SHORT,
        FLAT,
        UNI
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr pos() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr pos(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for pos
inline constexpr std::array<const char*, 4> pos_names = {{
    "LONG",
    "SHORT",
    "FLAT",
    "UNI",
}};

inline constexpr std::array<std::uint32_t, 4> pos_values = {{
    pos::LONG,
    pos::SHORT,
    pos::FLAT,
    pos::UNI,
}};

inline constexpr std::array<std::uint32_t, 3> pos_all = {{
    pos::LONG,
    pos::SHORT,
    pos::FLAT,
}};

using pos_pair = std::pair<pos, const char*>;

inline constexpr std::array<pos_pair, 4> pos_name_hash = {{
    pos_pair{pos::LONG, "LONG"},
    pos_pair{pos::SHORT, "SHORT"},
    pos_pair{pos::FLAT, "FLAT"},
    pos_pair{pos::UNI, "UNI"},
}};

// Type-safe array indexed by pos
template<typename T>
struct pos_array {
    std::array<T, 4> data;

    // Access operators
    constexpr T& operator[](pos idx) { return data[idx.value]; }
    constexpr const T& operator[](pos idx) const { return data[idx.value]; }

    constexpr T& at(pos idx) {
        if (idx.value >= data.size()) throw std::out_of_range("pos_array::at");
        return data[idx.value];
    }
    constexpr const T& at(pos idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("pos_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for pos

INLINE constexpr const char* to_string(pos n) {
    if (static_cast<std::size_t>(n.value) < pos_names.size()) {
        return pos_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t pos_num_syms() {
    return 4;
}

INLINE constexpr bool is_valid(pos n) {
    return (n.value < pos_num_syms() && n.value != pos::UNI);
}

INLINE bool pos_is_valid(std::string_view nam) {
    return std::find(pos_names.begin(), pos_names.end(), nam) != pos_names.end();
}

INLINE pos pos_index_of(std::string_view str) {
    auto it = std::find(pos_names.begin(), pos_names.end(), str);
    if (it == pos_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return pos(static_cast<std::uint32_t>(it - pos_names.begin()));
}

INLINE std::optional<pos> pos_try_parse(std::string_view str) {
    auto it = std::find(pos_names.begin(), pos_names.end(), str);
    if (it == pos_names.end()) {
        return std::nullopt;
    }
    return pos(static_cast<std::uint32_t>(it - pos_names.begin()));
}

struct pos_hash_t {
    bool contains(std::string_view key) const {
        return std::find(pos_names.begin(), pos_names.end(), key) != pos_names.end();
    }
    pos operator[](std::string_view key) const {
        return pos_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(pos_names.begin(), pos_names.end(), key);
        if (it != pos_names.end()) {
            return pos_name_hash.begin() + (it - pos_names.begin());
        }
        return pos_name_hash.end();
    }
    auto end() const { return pos_name_hash.end(); }
};
inline const pos_hash_t pos_hash;

// Operators for pos

INLINE std::ostream& operator<<(std::ostream& out, const pos& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::pos> {
        std::size_t operator()(en::pos e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
