// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct rv_freq {
    std::uint32_t value;
    enum {
        UNI,
        _10s,
        _5min
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr rv_freq() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr rv_freq(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for rv_freq
inline constexpr std::array<const char*, 3> rv_freq_names = {{
    "UNI",
    "10s",
    "5min",
}};

inline constexpr std::array<std::uint32_t, 3> rv_freq_values = {{
    rv_freq::UNI,
    rv_freq::_10s,
    rv_freq::_5min,
}};

using rv_freq_pair = std::pair<rv_freq, const char*>;

inline constexpr std::array<rv_freq_pair, 3> rv_freq_name_hash = {{
    rv_freq_pair{rv_freq::UNI, "UNI"},
    rv_freq_pair{rv_freq::_10s, "10s"},
    rv_freq_pair{rv_freq::_5min, "5min"},
}};

// Type-safe array indexed by rv_freq
template<typename T>
struct rv_freq_array {
    std::array<T, 3> data;

    // Access operators
    constexpr T& operator[](rv_freq idx) { return data[idx.value]; }
    constexpr const T& operator[](rv_freq idx) const { return data[idx.value]; }

    constexpr T& at(rv_freq idx) {
        if (idx.value >= data.size()) throw std::out_of_range("rv_freq_array::at");
        return data[idx.value];
    }
    constexpr const T& at(rv_freq idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("rv_freq_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for rv_freq

INLINE constexpr const char* to_string(rv_freq n) {
    if (static_cast<std::size_t>(n.value) < rv_freq_names.size()) {
        return rv_freq_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t rv_freq_num_syms() {
    return 3;
}

INLINE constexpr bool is_valid(rv_freq n) {
    return (n.value < rv_freq_num_syms() && n.value != rv_freq::UNI);
}

INLINE bool rv_freq_is_valid(std::string_view nam) {
    return std::find(rv_freq_names.begin(), rv_freq_names.end(), nam) != rv_freq_names.end();
}

INLINE rv_freq rv_freq_index_of(std::string_view str) {
    auto it = std::find(rv_freq_names.begin(), rv_freq_names.end(), str);
    if (it == rv_freq_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return rv_freq(static_cast<std::uint32_t>(it - rv_freq_names.begin()));
}

INLINE std::optional<rv_freq> rv_freq_try_parse(std::string_view str) {
    auto it = std::find(rv_freq_names.begin(), rv_freq_names.end(), str);
    if (it == rv_freq_names.end()) {
        return std::nullopt;
    }
    return rv_freq(static_cast<std::uint32_t>(it - rv_freq_names.begin()));
}

struct rv_freq_hash_t {
    bool contains(std::string_view key) const {
        return std::find(rv_freq_names.begin(), rv_freq_names.end(), key) != rv_freq_names.end();
    }
    rv_freq operator[](std::string_view key) const {
        return rv_freq_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(rv_freq_names.begin(), rv_freq_names.end(), key);
        if (it != rv_freq_names.end()) {
            return rv_freq_name_hash.begin() + (it - rv_freq_names.begin());
        }
        return rv_freq_name_hash.end();
    }
    auto end() const { return rv_freq_name_hash.end(); }
};
inline const rv_freq_hash_t rv_freq_hash;

// Operators for rv_freq

INLINE std::ostream& operator<<(std::ostream& out, const rv_freq& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::rv_freq> {
        std::size_t operator()(en::rv_freq e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
