// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct som {
    std::uint32_t value;
    enum {
        UNI,
        NEW,
        ACK,
        REJ,
        IREJ,
        CAN,
        CANACK,
        CANREJ,
        FILL,
        UNSTASH,
        PNLNOTIFY
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr som() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr som(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for som
inline constexpr std::array<const char*, 11> som_names = {{
    "UNI",
    "NEW",
    "ACK",
    "REJ",
    "IREJ",
    "CAN",
    "CANACK",
    "CANREJ",
    "FILL",
    "UNSTASH",
    "PNLNOTIFY",
}};

inline constexpr std::array<std::uint32_t, 11> som_values = {{
    som::UNI,
    som::NEW,
    som::ACK,
    som::REJ,
    som::IREJ,
    som::CAN,
    som::CANACK,
    som::CANREJ,
    som::FILL,
    som::UNSTASH,
    som::PNLNOTIFY,
}};

using som_pair = std::pair<som, const char*>;

inline constexpr std::array<som_pair, 11> som_name_hash = {{
    som_pair{som::UNI, "UNI"},
    som_pair{som::NEW, "NEW"},
    som_pair{som::ACK, "ACK"},
    som_pair{som::REJ, "REJ"},
    som_pair{som::IREJ, "IREJ"},
    som_pair{som::CAN, "CAN"},
    som_pair{som::CANACK, "CANACK"},
    som_pair{som::CANREJ, "CANREJ"},
    som_pair{som::FILL, "FILL"},
    som_pair{som::UNSTASH, "UNSTASH"},
    som_pair{som::PNLNOTIFY, "PNLNOTIFY"},
}};

// Type-safe array indexed by som
template<typename T>
struct som_array {
    std::array<T, 11> data;

    // Access operators
    constexpr T& operator[](som idx) { return data[idx.value]; }
    constexpr const T& operator[](som idx) const { return data[idx.value]; }

    constexpr T& at(som idx) {
        if (idx.value >= data.size()) throw std::out_of_range("som_array::at");
        return data[idx.value];
    }
    constexpr const T& at(som idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("som_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for som

INLINE constexpr const char* to_string(som n) {
    if (static_cast<std::size_t>(n.value) < som_names.size()) {
        return som_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t som_num_syms() {
    return 11;
}

INLINE constexpr bool is_valid(som n) {
    return (n.value < som_num_syms() && n.value != som::UNI);
}

INLINE bool som_is_valid(std::string_view nam) {
    return std::find(som_names.begin(), som_names.end(), nam) != som_names.end();
}

INLINE som som_index_of(std::string_view str) {
    auto it = std::find(som_names.begin(), som_names.end(), str);
    if (it == som_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return som(static_cast<std::uint32_t>(it - som_names.begin()));
}

INLINE std::optional<som> som_try_parse(std::string_view str) {
    auto it = std::find(som_names.begin(), som_names.end(), str);
    if (it == som_names.end()) {
        return std::nullopt;
    }
    return som(static_cast<std::uint32_t>(it - som_names.begin()));
}

struct som_hash_t {
    bool contains(std::string_view key) const {
        return std::find(som_names.begin(), som_names.end(), key) != som_names.end();
    }
    som operator[](std::string_view key) const {
        return som_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(som_names.begin(), som_names.end(), key);
        if (it != som_names.end()) {
            return som_name_hash.begin() + (it - som_names.begin());
        }
        return som_name_hash.end();
    }
    auto end() const { return som_name_hash.end(); }
};
inline const som_hash_t som_hash;

// Operators for som

INLINE std::ostream& operator<<(std::ostream& out, const som& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::som> {
        std::size_t operator()(en::som e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
