// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct th {
    std::uint32_t value;
    enum {
        HIT,
        TAK,
        UNI
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr th() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr th(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for th
inline constexpr std::array<const char*, 3> th_names = {{
    "HIT",
    "TAK",
    "UNI",
}};

inline constexpr std::array<std::uint32_t, 3> th_values = {{
    th::HIT,
    th::TAK,
    th::UNI,
}};

inline constexpr std::array<std::uint32_t, 2> th_all = {{
    th::HIT,
    th::TAK,
}};

using th_pair = std::pair<th, const char*>;

inline constexpr std::array<th_pair, 3> th_name_hash = {{
    th_pair{th::HIT, "HIT"},
    th_pair{th::TAK, "TAK"},
    th_pair{th::UNI, "UNI"},
}};

// Type-safe array indexed by th
template<typename T>
struct th_array {
    std::array<T, 3> data;

    // Access operators
    constexpr T& operator[](th idx) { return data[idx.value]; }
    constexpr const T& operator[](th idx) const { return data[idx.value]; }

    constexpr T& at(th idx) {
        if (idx.value >= data.size()) throw std::out_of_range("th_array::at");
        return data[idx.value];
    }
    constexpr const T& at(th idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("th_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for th

INLINE constexpr const char* to_string(th n) {
    if (static_cast<std::size_t>(n.value) < th_names.size()) {
        return th_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t th_num_syms() {
    return 3;
}

INLINE constexpr bool is_valid(th n) {
    return (n.value < th_num_syms() && n.value != th::UNI);
}

INLINE bool th_is_valid(std::string_view nam) {
    return std::find(th_names.begin(), th_names.end(), nam) != th_names.end();
}

INLINE th th_index_of(std::string_view str) {
    auto it = std::find(th_names.begin(), th_names.end(), str);
    if (it == th_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return th(static_cast<std::uint32_t>(it - th_names.begin()));
}

INLINE std::optional<th> th_try_parse(std::string_view str) {
    auto it = std::find(th_names.begin(), th_names.end(), str);
    if (it == th_names.end()) {
        return std::nullopt;
    }
    return th(static_cast<std::uint32_t>(it - th_names.begin()));
}

struct th_hash_t {
    bool contains(std::string_view key) const {
        return std::find(th_names.begin(), th_names.end(), key) != th_names.end();
    }
    th operator[](std::string_view key) const {
        return th_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(th_names.begin(), th_names.end(), key);
        if (it != th_names.end()) {
            return th_name_hash.begin() + (it - th_names.begin());
        }
        return th_name_hash.end();
    }
    auto end() const { return th_name_hash.end(); }
};
inline const th_hash_t th_hash;

// Operators for th

INLINE std::ostream& operator<<(std::ostream& out, const th& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::th> {
        std::size_t operator()(en::th e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
