// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"

namespace en {


struct trader {
    std::uint32_t value;
    enum {
        BYHAND,
        OCCAMZNUB,
        OCCAMNQ,
        OCCAMES,
        OCCAMZN,
        OCCAMZB,
        OCCAMLIQ,
        OCCAMUST,
        EOM,
        ALL,
        SIMULATOR,
        BFA2,
        UNI
    };

    // Implicit conversion to uint for backward compatibility
    constexpr operator std::uint32_t() const { return value; }
    // Default constructor
    constexpr trader() : value(std::numeric_limits<std::uint32_t>::max()) {}
    // Constructors from enum values (use implicit uint conversion)
    constexpr trader(std::uint32_t _value) : value(_value) {}
};

// Constexpr lookup tables for trader
inline constexpr std::array<const char*, 13> trader_names = {{
    "BYHAND",
    "OCCAMZNUB",
    "OCCAMNQ",
    "OCCAMES",
    "OCCAMZN",
    "OCCAMZB",
    "OCCAMLIQ",
    "OCCAMUST",
    "EOM",
    "ALL",
    "SIMULATOR",
    "BFA2",
    "UNI",
}};

inline constexpr std::array<std::uint32_t, 13> trader_values = {{
    trader::BYHAND,
    trader::OCCAMZNUB,
    trader::OCCAMNQ,
    trader::OCCAMES,
    trader::OCCAMZN,
    trader::OCCAMZB,
    trader::OCCAMLIQ,
    trader::OCCAMUST,
    trader::EOM,
    trader::ALL,
    trader::SIMULATOR,
    trader::BFA2,
    trader::UNI,
}};

inline constexpr std::array<std::uint32_t, 12> trader_all = {{
    trader::BYHAND,
    trader::OCCAMZNUB,
    trader::OCCAMNQ,
    trader::OCCAMES,
    trader::OCCAMZN,
    trader::OCCAMZB,
    trader::OCCAMLIQ,
    trader::OCCAMUST,
    trader::EOM,
    trader::ALL,
    trader::SIMULATOR,
    trader::BFA2,
}};

using trader_pair = std::pair<trader, const char*>;

inline constexpr std::array<trader_pair, 13> trader_name_hash = {{
    trader_pair{trader::BYHAND, "BYHAND"},
    trader_pair{trader::OCCAMZNUB, "OCCAMZNUB"},
    trader_pair{trader::OCCAMNQ, "OCCAMNQ"},
    trader_pair{trader::OCCAMES, "OCCAMES"},
    trader_pair{trader::OCCAMZN, "OCCAMZN"},
    trader_pair{trader::OCCAMZB, "OCCAMZB"},
    trader_pair{trader::OCCAMLIQ, "OCCAMLIQ"},
    trader_pair{trader::OCCAMUST, "OCCAMUST"},
    trader_pair{trader::EOM, "EOM"},
    trader_pair{trader::ALL, "ALL"},
    trader_pair{trader::SIMULATOR, "SIMULATOR"},
    trader_pair{trader::BFA2, "BFA2"},
    trader_pair{trader::UNI, "UNI"},
}};

// Type-safe array indexed by trader
template<typename T>
struct trader_array {
    std::array<T, 13> data;

    // Access operators
    constexpr T& operator[](trader idx) { return data[idx.value]; }
    constexpr const T& operator[](trader idx) const { return data[idx.value]; }

    constexpr T& at(trader idx) {
        if (idx.value >= data.size()) throw std::out_of_range("trader_array::at");
        return data[idx.value];
    }
    constexpr const T& at(trader idx) const {
        if (idx.value >= data.size()) throw std::out_of_range("trader_array::at");
        return data[idx.value];
    }

    // Standard container interface
    constexpr auto begin() { return data.begin(); }
    constexpr auto end() { return data.end(); }
    constexpr auto begin() const { return data.begin(); }
    constexpr auto end() const { return data.end(); }
    constexpr auto cbegin() const { return data.cbegin(); }
    constexpr auto cend() const { return data.cend(); }
    constexpr std::size_t size() const { return data.size(); }
    constexpr bool empty() const { return false; }
    constexpr T& front() { return data.front(); }
    constexpr const T& front() const { return data.front(); }
    constexpr T& back() { return data.back(); }
    constexpr const T& back() const { return data.back(); }
    constexpr T* ptr() { return data.data(); }
    constexpr const T* ptr() const { return data.data(); }
};

// Utility functions for trader

INLINE constexpr const char* to_string(trader n) {
    if (static_cast<std::size_t>(n.value) < trader_names.size()) {
        return trader_names[n.value];
    }
    return "INVALID";
}

INLINE constexpr std::size_t trader_num_syms() {
    return 13;
}

INLINE constexpr bool is_valid(trader n) {
    return (n.value < trader_num_syms() && n.value != trader::UNI);
}

INLINE bool trader_is_valid(std::string_view nam) {
    return std::find(trader_names.begin(), trader_names.end(), nam) != trader_names.end();
}

INLINE trader trader_index_of(std::string_view str) {
    auto it = std::find(trader_names.begin(), trader_names.end(), str);
    if (it == trader_names.end()) {
        std::cerr << str << " not found" << std::endl;
        ERR("not found");
    }
    return trader(static_cast<std::uint32_t>(it - trader_names.begin()));
}

INLINE std::optional<trader> trader_try_parse(std::string_view str) {
    auto it = std::find(trader_names.begin(), trader_names.end(), str);
    if (it == trader_names.end()) {
        return std::nullopt;
    }
    return trader(static_cast<std::uint32_t>(it - trader_names.begin()));
}

struct trader_hash_t {
    bool contains(std::string_view key) const {
        return std::find(trader_names.begin(), trader_names.end(), key) != trader_names.end();
    }
    trader operator[](std::string_view key) const {
        return trader_index_of(key);
    }
    auto find(std::string_view key) const {
        auto it = std::find(trader_names.begin(), trader_names.end(), key);
        if (it != trader_names.end()) {
            return trader_name_hash.begin() + (it - trader_names.begin());
        }
        return trader_name_hash.end();
    }
    auto end() const { return trader_name_hash.end(); }
};
inline const trader_hash_t trader_hash;

// Operators for trader

INLINE std::ostream& operator<<(std::ostream& out, const trader& p) {
    return out << to_string(p);
}
}


// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {
    template<> struct hash<en::trader> {
        std::size_t operator()(en::trader e) const noexcept {
            return std::hash<std::uint32_t>{}(e.value);
        }
    };
}
