// Copyright (c) 2026 Vincent Mayeski / M2 Tech (16425640 Canada Inc.).
// Contact: v@m2te.ch | https://www.linkedin.com/in/vmayeski/
//
// Licensed under the MIT License. See LICENSE file in the project root.

//! Actor core: the `Actor` trait, O(1) integer-id dispatch (`handle_messages!`),
//! and `ActorRef` providing both `fast_send` (on-stack, synchronous, inline) and
//! `send` (async via `BQueue`).
//!
//! ## fast_send (the headline)
//! `ActorRef::fast_send(&msg)` takes the target's **per-actor lock**, runs the
//! target's handler **inline on the caller's thread**, and returns the reply —
//! no queue, no thread hop, and the request message is borrowed (`&dyn Message`),
//! so the caller can keep it **on the stack**. Works from any actor to any other
//! actor. The per-actor lock is the Rust analog of C++'s `fast_send_mutex`
//! (`Actor.cpp:98,115`), taken by both `fast_send` and the async run loop; it is
//! ~free when uncontended, which is why fast_send is "pretty much a function call".
//!
//! Reentrancy: the per-actor lock is non-reentrant, so any `fast_send` call
//! chain that cycles back to an actor already executing on this thread
//! deadlocks — not just direct self-sends (A→A) but any cycle (A→B→A). Keep
//! `fast_send` chains acyclic. (C++ has the same hazard via `fast_send_mutex`.)

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};

use crate::message::Message;
// Bring MsgId into scope so `Shutdown::ID` resolves in the run loop.
use crate::message::MsgId;
use crate::owner::MsgBox;
use crate::queue::BQueue;

/// Size of the flat dispatch table. Message ids must be `< HANDLER_CACHE_SIZE`.
pub const HANDLER_CACHE_SIZE: usize = 1024;

/// Default mailbox ring capacity (matches C++ `ACTOR_BQUEUE_SIZE`).
pub const ACTOR_BQUEUE_SIZE: usize = 64;

/// Type-erased handler slot for the dispatch table of actor type `A`.
pub type HandlerFn<A> = fn(&mut A, &dyn Message, &mut ActorContext<'_>);

/// Trait implemented by all actors. `process_message` is normally generated by
/// the `handle_messages!` macro (O(1) dispatch by integer id).
pub trait Actor: Send + 'static {
    /// Called once before the run loop starts processing async messages.
    fn init(&mut self, _ctx: &mut ActorContext<'_>) {}
    /// Called once after the run loop stops.
    fn end(&mut self) {}
    /// Dispatch a message to the right handler. Provided by `handle_messages!`.
    fn process_message(&mut self, msg: &dyn Message, ctx: &mut ActorContext<'_>);
}

/// Context passed to a handler: who to reply to, and this actor's own ref.
///
/// `self_ref` is **borrowed**, not owned, so building a context per message
/// (or per `fast_send`) costs no `Arc` clone on the hot path — the clone is
/// deferred to `reply()`/`self_ref()`, which are the only places a caller
/// actually needs an owned handle.
pub struct ActorContext<'a> {
    sender: Option<ActorRef>,
    self_ref: Option<&'a ActorRef>,
    reply_slot: Option<MsgBox>,
    is_fast: bool,
}

impl<'a> ActorContext<'a> {
    fn new(sender: Option<ActorRef>, self_ref: Option<&'a ActorRef>, is_fast: bool) -> Self {
        ActorContext {
            sender,
            self_ref,
            reply_slot: None,
            is_fast,
        }
    }

    /// Reply to the current message.
    ///
    /// Under `fast_send`, the reply is handed straight back to the caller.
    /// Under async `send`, it is delivered to the sender's mailbox.
    ///
    /// Accepts `Box::new(msg)` (heap) or `MsgBox::pooled(msg)` (pooled).
    pub fn reply(&mut self, msg: impl Into<MsgBox>) {
        let msg = msg.into();
        if self.is_fast {
            self.reply_slot = Some(msg);
        } else if let Some(s) = &self.sender {
            s.send(msg, self.self_ref.cloned());
        }
        // else: no sender, reply dropped.
    }

    /// This actor's own reference (to pass as the sender of outgoing messages).
    pub fn self_ref(&self) -> Option<ActorRef> {
        self.self_ref.cloned()
    }

    /// The sender of the current message, if any.
    pub fn sender(&self) -> Option<ActorRef> {
        self.sender.clone()
    }
}

/// Shared per-actor state: the actor behind its per-actor lock, plus its mailbox.
///
/// Public only because `ActorRef::Local` names it; not part of the public API
/// (all fields are crate-private).
#[doc(hidden)]
pub struct ActorCell {
    pub(crate) name: String,
    /// Per-actor lock — the `fast_send_mutex` analog. Guards ALL dispatch
    /// (both `fast_send` and the async run loop) so any thread can fast_send here.
    pub(crate) actor: Mutex<Box<dyn Actor>>,
    /// Async mailbox.
    pub(crate) queue: BQueue<Envelope>,
    /// Run-loop liveness flag.
    pub(crate) running: AtomicBool,
}

/// An async message plus its sender (for replies).
pub(crate) struct Envelope {
    pub(crate) msg: MsgBox,
    pub(crate) sender: Option<ActorRef>,
}

/// A cloneable handle (address) to an actor. Supports `send` and `fast_send`.
///
/// `Local` wraps the actor's cell (in-process). With the `interop` feature, a
/// `Cpp` variant reaches a C++ actor over the FFI bridge (see [`crate::interop`]);
/// callers use the same `send`/`fast_send` API regardless of the target's language.
#[derive(Clone)]
pub enum ActorRef {
    Local(Arc<ActorCell>),
    #[cfg(feature = "interop")]
    Cpp(crate::interop::CppRef),
}

impl ActorRef {
    /// Construct a local reference (internal).
    pub(crate) fn local(cell: Arc<ActorCell>) -> Self {
        ActorRef::Local(cell)
    }

    /// The actor's name.
    pub fn name(&self) -> &str {
        match self {
            ActorRef::Local(cell) => &cell.name,
            #[cfg(feature = "interop")]
            ActorRef::Cpp(r) => r.name(),
        }
    }

    /// Async, fire-and-forget: enqueue an owned message into the target's mailbox.
    ///
    /// Accepts `Box::new(msg)` (heap) or `MsgBox::pooled(msg)` (pooled).
    pub fn send(&self, msg: impl Into<MsgBox>, sender: Option<ActorRef>) {
        match self {
            ActorRef::Local(cell) => cell.queue.push(Envelope { msg: msg.into(), sender }),
            #[cfg(feature = "interop")]
            ActorRef::Cpp(r) => r.send(msg.into(), sender),
        }
    }

    /// Synchronous on-stack call: run the target's handler inline on THIS thread
    /// and return its reply. The request `msg` is borrowed — keep it on the stack.
    ///
    /// Takes the target's per-actor lock (uncontended ≈ a function call). Any
    /// actor may call this on any other actor. Never call it on yourself from
    /// within your own handler (non-reentrant lock → deadlock).
    ///
    /// For a `Cpp` target the handler runs inline over FFI but **no reply can cross
    /// the C ABI**, so this returns `None` (delivered, no synchronous reply).
    pub fn fast_send(&self, msg: &dyn Message, sender: Option<ActorRef>) -> Option<MsgBox> {
        match self {
            ActorRef::Local(cell) => {
                let mut ctx = ActorContext::new(sender, Some(self), true);
                // Recover from a poisoned lock (a prior handler panicked) instead of
                // cascading that panic into this caller — one bad message must not
                // brick the actor for everyone else.
                let mut guard = cell.actor.lock().unwrap_or_else(|e| e.into_inner());
                guard.process_message(msg, &mut ctx);
                ctx.reply_slot
            }
            #[cfg(feature = "interop")]
            ActorRef::Cpp(r) => r.fast_send(msg, sender),
        }
    }
}

/// Run loop for one actor (executed on the actor's own thread by the Manager).
/// Pops the mailbox and dispatches under the per-actor lock until Shutdown.
pub(crate) fn run_actor(cell: Arc<ActorCell>) {
    let self_ref = ActorRef::local(cell.clone());

    // init() under the lock. `unwrap_or_else(into_inner)` recovers a poisoned
    // lock so a panic in one actor can't cascade to others via `.unwrap()`.
    {
        let mut ctx = ActorContext::new(None, Some(&self_ref), false);
        let mut guard = cell.actor.lock().unwrap_or_else(|e| e.into_inner());
        guard.init(&mut ctx);
    }

    while cell.running.load(Ordering::Relaxed) {
        let (env, _last) = cell.queue.pop();
        let is_shutdown = env.msg.message_id() == crate::messages::Shutdown::ID;

        {
            let mut ctx = ActorContext::new(env.sender, Some(&self_ref), false);
            let mut guard = cell.actor.lock().unwrap_or_else(|e| e.into_inner());
            guard.process_message(env.msg.as_message(), &mut ctx);
        }

        if is_shutdown {
            cell.running.store(false, Ordering::Relaxed);
            break;
        }
    }

    let mut guard = cell.actor.lock().unwrap_or_else(|e| e.into_inner());
    guard.end();
}

/// Generate `Actor::process_message` as an O(1) dispatch by integer id — the
/// direct analog of C++'s `handler_cache`. Builds a per-type table (once, lazily)
/// mapping `message_id` → a type-erased handler that downcasts and calls the
/// concrete method.
///
/// ```ignore
/// handle_messages!(MyActor,
///     Ping  => on_ping,
///     Start => on_start,
/// );
/// ```
#[macro_export]
macro_rules! handle_messages {
    ($actor:ty, $($msg:ty => $handler:ident),+ $(,)?) => {
        // Compile-time bound check: an id >= HANDLER_CACHE_SIZE would index the
        // dispatch table out of bounds at runtime, so reject it at build time.
        $(
            const _: () = assert!(
                (<$msg as $crate::MsgId>::ID as usize) < $crate::HANDLER_CACHE_SIZE,
                "message id must be < HANDLER_CACHE_SIZE",
            );
        )+

        impl $actor {
            fn __dispatch_table(
            ) -> &'static ::std::vec::Vec<::std::option::Option<$crate::HandlerFn<$actor>>> {
                static TABLE: ::std::sync::OnceLock<
                    ::std::vec::Vec<::std::option::Option<$crate::HandlerFn<$actor>>>,
                > = ::std::sync::OnceLock::new();
                TABLE.get_or_init(|| {
                    let mut t: ::std::vec::Vec<
                        ::std::option::Option<$crate::HandlerFn<$actor>>,
                    > = ::std::vec![None; $crate::HANDLER_CACHE_SIZE];
                    $(
                        let h: $crate::HandlerFn<$actor> = |actor: &mut $actor,
                                                             msg: &dyn $crate::Message,
                                                             ctx: &mut $crate::ActorContext<'_>| {
                            // Graceful downcast: if the id maps to a different type
                            // (a duplicate-id misconfiguration), DROP the message
                            // rather than panic — a panic here fires under the
                            // actor lock and would poison it. Debug builds assert.
                            if let ::std::option::Option::Some(m) =
                                msg.as_any().downcast_ref::<$msg>()
                            {
                                actor.$handler(m, ctx);
                            } else {
                                debug_assert!(
                                    false,
                                    "actors: message id/type mismatch (duplicate message id?)"
                                );
                            }
                        };
                        t[<$msg as $crate::MsgId>::ID as usize] = Some(h);
                    )+
                    t
                })
            }
        }

        impl $crate::Actor for $actor {
            #[inline]
            fn process_message(
                &mut self,
                msg: &dyn $crate::Message,
                ctx: &mut $crate::ActorContext<'_>,
            ) {
                let id = msg.message_id() as usize;
                if let Some(Some(h)) = Self::__dispatch_table().get(id) {
                    h(self, msg, ctx);
                }
            }
        }
    };
}
