#pragma once

/*
 * Copyright (c) 2026 Vincent Mayeski / M2 Tech (16425640 Canada Inc.).
 * Contact: v@m2te.ch | https://www.linkedin.com/in/vmayeski/
 *
 * Licensed under the MIT License. See LICENSE file in the project root.
 */

#include <cstdio>
#include <map>
#include <vector>
#include <variant>
#include <boost/unordered/unordered_flat_map.hpp>

#include "chutil/Macros.hpp"
#include "actors/Actor.hpp"
#include "bfile/r_l3.hpp"
#include "enum/e_names.hpp"
#include "frame/mda/msg/Data.hpp"
#include "frame/ref/RefData.hpp"
#include "mdp3/msg/ParsedMsg.hpp"
#include "mdp3/msg/AssetMap.hpp"
#include "mdp3/msg/OrderMap.hpp"
#include "mdp3/msg/ResetMBO.hpp"

namespace mdp3
{
  // The single serialization point for the parallel decode path.
  //
  // The DecodeWorkers parse messages in parallel and send their entries here as
  // ParsedMsg batches, tagged with a dense per-message order_seq. The
  // Reconstructor:
  //   1. RESEQUENCES: drains order_seq = expected, expected+1, ... (buffering
  //      out-of-order batches) so entries apply in exact wire order.
  //   2. OWNS all order-dependent state -- orderid_to_securityid (from book/trade)
  //      and asset_map_ (from definitions) -- and does the routing (asset lookup
  //      -> send to TachBook[asset]). Being single-threaded IS the
  //      synchronization; no locks.
  //
  // EVERY live message flows through here (book, trade, definition, reset, ...),
  // so on the live feed this actor is the sole writer of those maps -- there is
  // no inline handler_if copy competing on the parallel path. Recovery does run
  // through handler_if, so its state is forwarded in: asset_map_ is seeded by
  // AssetMap messages (instrument recovery) and orderid_to_securityid_ by OrderMap
  // messages (snapshot/data recovery), both applied on THIS actor's thread before
  // the live feed resumes. mbo_order_books is set once at startup and read-only
  // during trading (shared by const ref).
  //
  // No burst-end / end-of-packet signal is emitted, and none is needed. The
  // downstream EndOfBurst that lights/SOM/probes subscribe to is generated by the
  // TachBook itself in publish_book(), once per book-changing record -- it does
  // not consume the MDP3 BurstEnd/EOB (TachBook logs l3_eob_t as unexpected). So
  // routing each MBO record to the book (below) is sufficient; the book publishes
  // on its own. EndOfPacket only resets handler_if's pkt_entry_idx_ latency
  // counter, which this path does not stamp -- generating it would be wasted work.
  class Reconstructor : public actors::Actor
  {
  public:
    // chan (not venue) keys the name. The old "Reconstructor_%d" was keyed on
    // the VENUE, and channels 310/318/344 share one venue -- so a second CME
    // channel collided in Manager. "_P" marks the parallel path, matching
    // DataDecoder_P_310 / DecodeWorker_P_310_0.
    // treas_only MUST match the handler_if<_, TreasOnly> for this channel: it
    // selects the RefData lookup key in apply_def exactly as handler_if does
    // (asset for treasury futures, symbol otherwise). Wired from the same flag in
    // kaspr so the two can never disagree.
    Reconstructor(const std::vector<actor_ptr> &mbo_order_books,
                  en::x xchg,
                  uint32_t chan,
                  const char *path_tag = "P",
                  bool treas_only = false)
        : mbo_order_books_(mbo_order_books),
          xchg_(xchg),
          treas_only_(treas_only)
    {
      snprintf(name_, sizeof(name_), "Reconstructor_%s_%u", path_tag, chan);
      MESSAGE_HANDLER(msg::ParsedMsg, on_parsed);
      MESSAGE_HANDLER(msg::AssetMap, on_asset_map);
      MESSAGE_HANDLER(msg::OrderMap, on_order_map);
      MESSAGE_HANDLER(msg::ResetMBO, on_reset);
    }

    const char *get_name() const override { return name_; }

  private:
    void on_parsed(const msg::ParsedMsg *pm) noexcept
    {
      if (pm->order_seq == expected_seq_)
      {
        apply(pm->entries);
        ++expected_seq_;
        drain();
      }
      else
      {
        // out of order -> buffer (copy: the message is freed after this handler)
        buffer_[pm->order_seq] = pm->entries;
      }
    }

    // Apply any buffered batches that are now contiguous with expected_seq_.
    void drain() noexcept
    {
      while (!buffer_.empty() && buffer_.begin()->first == expected_seq_)
      {
        apply(buffer_.begin()->second);
        buffer_.erase(buffer_.begin());
        ++expected_seq_;
      }
    }

    void apply(const std::vector<bfile::l3_t> &entries) noexcept
    {
      for (const auto &e : entries)
      {
        if (std::holds_alternative<bfile::l3_mbo_v2_t>(e))
          apply_book(std::get<bfile::l3_mbo_v2_t>(e));
        else if (std::holds_alternative<bfile::l3_mbo_trd_v2_t>(e))
          apply_trade(std::get<bfile::l3_mbo_trd_v2_t>(e));
        else if (std::holds_alternative<bfile::l3_fdf_t>(e))
          apply_def(std::get<bfile::l3_fdf_t>(e));
        else if (std::holds_alternative<bfile::l3_chr_v2_t>(e))
          orderid_to_securityid_.clear(); // ChannelReset, applied in wire order
      }
    }

    // Order add/modify/delete: mutate the orderid map, then route by securityID.
    // Mirrors handler_if::MDIncrementalRefreshBook's stateful tail.
    void apply_book(const bfile::l3_mbo_v2_t &l3) noexcept
    {
      if (l3.orderUpdateAction == 0) // New
        orderid_to_securityid_[l3.orderID] = l3.securityID;
      else if (l3.orderUpdateAction == 2) // Delete
        orderid_to_securityid_.erase(l3.orderID);

      route(l3.securityID, l3);
      // TODO: if (l3.endOfEvent) emit_burstend();
    }

    // Trade carries only orderID: resolve securityID via the map (populated by a
    // prior New), then route. Mirrors handler_if::MDIncrementalRefreshTradeSummary.
    void apply_trade(const bfile::l3_mbo_trd_v2_t &l3) noexcept
    {
      auto oit = orderid_to_securityid_.find(l3.orderID);
      if (oit == orderid_to_securityid_.end()) [[unlikely]]
        return; // order not known -> not in universe
      route(oit->second, l3);
      // TODO: if (l3.endOfEvent) emit_burstend();
    }

    // Instrument definition in the ordered stream: resolve the asset off the
    // RefData singleton (same lookup handler_if does) and update THIS actor's
    // asset_map_, in wire order with the book stream. This replaces the
    // out-of-band AssetMap message for the parallel path.
    //
    // Minimal by design: it establishes securityID -> asset_id for routing. It
    // does NOT re-run handler_if's full RefData configuration (price units, cfi,
    // security group). Definitions arrive during instrument recovery, which still
    // runs through handler_if and configures RefData there; on the live
    // incremental feed they are essentially absent. So this only has to keep
    // routing correct.
    //
    // Key selection mirrors handler_if::MDInstrumentDefinitionFuture EXACTLY:
    // treasury futures key RefData by asset, everything else by symbol. Driven by
    // treas_only_ (== the channel's handler_if<_, TreasOnly>), so the parallel
    // path resolves to the same asset_id the serial/recovery path would.
    void apply_def(const bfile::l3_fdf_t &l3) noexcept
    {
      if (l3.updateAction != 'A' && l3.updateAction != 'M')
        return;
      const std::string key = treas_only_ ? std::string(l3.asset) : std::string(l3.sym);
      auto a = frame::ref::RefData::inst().get_asset(key);
      if (a)
        asset_map_[l3.securityID] = a->id;
    }

    // A definition mapped securityID -> asset_id (sent by handler_if, e.g. during
    // instrument recovery). Update our own copy on THIS actor's thread so route()
    // never touches the shared map.
    void on_asset_map(const msg::AssetMap *m) noexcept
    {
      asset_map_[m->securityID] = m->asset_id;
    }

    // A snapshot-recovered resting order mapped orderID -> securityID (sent by
    // handler_if from SnapshotFullRefreshOrderBook during data recovery). Seed
    // our orderID map on THIS actor's thread so a live trade referencing that
    // order resolves. These arrive before the live feed resumes (recovery
    // completes first), so they land ahead of any live ParsedMsg -- no need to
    // resequence them into the order_seq stream.
    void on_order_map(const msg::OrderMap *m) noexcept
    {
      orderid_to_securityid_[m->orderID] = m->securityID;
    }

    // ChannelReset: the exchange cleared the book. Drop the orderID map so a
    // reused orderID cannot misroute. Leave asset_map_ (definitions persist) and
    // the resequence state (order_seq/expected_seq/buffer_) untouched -- those
    // stay in lockstep with DataDecoder, so clearing them would stall the stream.
    void on_reset(const msg::ResetMBO *) noexcept
    {
      orderid_to_securityid_.clear();
    }

    // securityID -> asset_id -> TachBook[asset_id]; send the l3 as a raw Data.
    template <class L3>
    void route(int32_t securityID, const L3 &l3) noexcept
    {
      auto it = asset_map_.find(securityID);
      if (it == asset_map_.end()) [[unlikely]]
        return; // not in universe (yet)
      const int32_t asset_id = it->second;
      if (asset_id < 0 || static_cast<size_t>(asset_id) >= mbo_order_books_.size()) [[unlikely]]
        return;
      const auto book = mbo_order_books_[asset_id];
      if (!book) [[unlikely]]
        return;
      auto *d = new frame::mda::msg::Data(/*israw=*/true);
      d->l3 = l3;
      book->send(d, this);
    }

    // Owned: mutated only here (single-threaded), so no lock.
    boost::unordered_flat_map<uint64_t, int32_t> orderid_to_securityid_;
    // Owned: fed by handler_if via AssetMap messages and applied on THIS actor's
    // thread -- no shared-map race with the inline definition path.
    boost::unordered_flat_map<int32_t, int32_t> asset_map_;
    // Shared read-only: set once at startup (kaspr), never written afterwards.
    const std::vector<actor_ptr> &mbo_order_books_;

    // Resequence buffer: order_seq -> that message's entries. std::map keeps keys
    // sorted so the smallest buffered order_seq is begin().
    std::map<uint64_t, std::vector<bfile::l3_t>> buffer_;
    uint64_t expected_seq_ = 0;

    en::x xchg_;
    // Matches handler_if<_, TreasOnly>; picks the apply_def RefData lookup key.
    bool  treas_only_ = false;
    char  name_[256];
  };
}
