# Copyright (c) 2026 Vincent Mayeski / M2 Tech (16425640 Canada Inc.).
#
# Licensed under the MIT License. See LICENSE file in the project root.

include $(KSPRPROJ)/mk/glob_begin.mk

LIBSRC = random.cpp Stats.cpp
NAM = oogsl

include $(KSPRPROJ)/mk/lib_template.mk
