#!/usr/bin/env python3
# Copyright (c) 2026 Vincent Mayeski / M2 Tech (16425640 Canada Inc.).
# Contact: mayeski@gmail.com | https://www.linkedin.com/in/vmayeski/
#
# Licensed under the MIT License. See LICENSE file in the project root.
"""Generate the tradable-session list from the official CME Equity calendar.

    python3 gen_sessions.py 2025-01-01 2025-12-31 > market_sessions.tsv

Needs pandas_market_calendars, which is NOT a dependency of anything else here
and is deliberately not required at run time: run_grid.sh reads the generated
TSV, so the sweep has no Python dependency and the calendar it used is a file in
git that can be diffed and reviewed. Regenerate when the corpus gains a year.

The system Python is externally managed (PEP 668), so install into a venv:

    python3 -m venv ~/tmp/calvenv
    ~/tmp/calvenv/bin/pip install pandas_market_calendars
    ~/tmp/calvenv/bin/python gen_sessions.py 2025-01-01 2025-12-31 > market_sessions.tsv

Why a calendar rather than a hand-written holiday list or a file-size rule:

  * A size rule cannot see an EARLY CLOSE. MLK Day 2025 is a 60 MB file that
    looks healthy because its overnight session is full, but CME closes equities
    at 13:00 and the probe gets 22 windows instead of 36.
  * A hand-written list goes stale silently, and one-off closures are exactly
    what it misses -- 2025-01-09, the day of mourning for President Carter, is
    in no recurring holiday rule. The calendar has it: that date is simply
    absent from the schedule.

Emits one row per calendar day the exchange is open, with its real RTH open and
close, and whether it covers the window the probe measures (09:30-15:30 ET).
An EARLY CLOSE is not a small normal day -- it is a truncated session drawn from
a different regime -- so it is marked not-usable just like a full closure.
"""
import sys
import pandas as pd
import pandas_market_calendars as mcal

start, end = sys.argv[1], sys.argv[2]
cal = mcal.get_calendar('CME_Equity')
sched = cal.schedule(start_date=start, end_date=end)

ET = 'America/New_York'
rows = []
for day, r in sched.iterrows():
    o = r['market_open'].tz_convert(ET)
    c = r['market_close'].tz_convert(ET)
    # Anchor on the CLOSE date, not the open. A CME_Equity session opens at
    # 18:00 ET the PREVIOUS calendar day and closes 17:00 ET on the index date,
    # so the RTH window we measure belongs to the closing day. Anchoring on the
    # open put 09:30 a day early and marked every session short.
    base = c.normalize()
    need_o = base + pd.Timedelta(hours=9, minutes=30)
    need_c = base + pd.Timedelta(hours=15, minutes=30)
    usable = (o <= need_o) and (c >= need_c)
    rows.append((day.strftime('%Y%m%d'), o.strftime('%H:%M'), c.strftime('%H:%M'),
                 'usable' if usable else 'short'))

print('# date\topen_et\tclose_et\tstatus')
print('# generated by sim/scripts/gen_sessions.py from the CME_Equity calendar')
print('# "short" = closed or early close; does not cover 09:30-15:30 ET')
for r in rows:
    print('\t'.join(r))
