#
# Copyright (c) 2026 Vincent Mayeski / M2 Tech (16425640 Canada Inc.).
# Licensed under the MIT License. See LICENSE file in the project root.
#
# obcmp: feeds one instrument of a capture to OB and TachBook side by side
# and writes each book's TradeNotify and best bid/offer, for comparison with
# obcmp_report.py. See the header of obcmp.cpp. Not part of `make all`:
#   ./build.sh -C unit_test/obcmp
include $(KSPRPROJ)/mk_kaspr/glob_begin.mk

SRC = obcmp.cpp
APPNAM = obcmp

include $(KSPRPROJ)/mk_kaspr/app_template.mk
