/*
 * Copyright (c) 2026 Vincent Mayeski / M2 Tech (16425640 Canada Inc.).
 * Contact: mayeski@gmail.com | https://www.linkedin.com/in/vmayeski/
 *
 * Licensed under the MIT License. See LICENSE file in the project root.
 */

/*
 * bin_replay_bbo -- replay one .bin file, build books, tape top-of-book.
 *
 * Chain:  BFA (reads .bin)  ->  OB per securityID  ->  BboRecorder (gz CSV)
 *
 * Contrast with dbento_pcap_to_bin, which reads pcaps and dumps raw MDP3 to a
 * .bin (PCAPReader -> MsgBuf -> MessageProcessor -> handler_if -> BinRecorder).
 * Here the input IS the .bin: BFA decodes it back into MBO/trade records and
 * feeds each OB, which reconstructs the book and publishes BBBOChg to its
 * subscribers. Our subscriber is the BboRecorder.
 *
 * Universe is required. Every OB has to be sized from a real daily limit
 * (SimKaspr's rule: asserts maxpx > 1 before building the ladder), and the .bin
 * is not guaranteed to carry the l3_lim record for every symbol before its
 * first MBO, so we preload from the per-day universe JSON that
 * scripts/build_universe_day.sh writes.
 */

#include <algorithm>
#include <cctype>
#include <csignal>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <fenv.h>
#include <fstream>
#include <iostream>
#include <string>
#include <unordered_map>
#include <vector>

#include <boost/filesystem.hpp>
#include <boost/format.hpp>
#include <boost/program_options.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/thread/thread.hpp>

#include "chutil/Macros.hpp"
#include "chutil/sig_hand.hpp"

#include "actors/act/Manager.hpp"
#include "actors/act/Group.hpp"

#include "logger/act/Logger.hpp"

#include "enum/e_names.hpp"
#include "frame/ref/RefData.hpp"
#include "frame/mda/act/BFA.hpp"
#include "frame/ob/act/OB.hpp"
#include "frame/ob/if/BboRecorder.hpp"

namespace po = boost::program_options;

namespace {

// Try to pull YYYYMMDD out of a filename like "318.20250310.databento.bin".
// Purely informational -- used only for the CSV label and log line.
static std::string date_from_datafile(const std::string &path)
{
  size_t slash = path.find_last_of('/');
  std::string base = (slash == std::string::npos) ? path : path.substr(slash + 1);
  for (size_t i = 0; i + 8 <= base.size(); ++i)
  {
    if (std::all_of(base.begin() + i, base.begin() + i + 8, ::isdigit) &&
        (i == 0 || !isdigit(base[i - 1])) &&
        (i + 8 == base.size() || !isdigit(base[i + 8])))
    {
      std::string cand = base.substr(i, 8);
      if (cand.substr(0, 2) == "20") return cand;
    }
  }
  return "";
}

// One registered contract: the driver builds an OB for each of these.
struct Contract
{
  std::string symbol;   // e.g. "NQH5"
  std::string asset;    // e.g. "NQ"
  int32_t     sec_id;   // CME securityID
  double      mpi;      // minPriceIncrement (native units)
  double      hi;       // high_limit_px (native units)
  en::x       venue;
};

// Read the universe JSON produced by dbento_pcap_parse/scripts/build_universe_day.sh.
// Returns every FDF/FUT with a positive high_limit_px (SimKaspr's ladder-sizing
// rule -- OB asserts maxpx > 1). If asset_filter is non-empty, keep only
// contracts whose "asset" root matches.
std::vector<Contract> load_universe(const std::string &universe_json,
                                    const std::string &asset_filter,
                                    en::x default_venue)
{
  boost::property_tree::ptree pt;
  try {
    boost::property_tree::read_json(universe_json, pt);
  } catch (const std::exception &e) {
    ERRF(boost::format("bin_replay_bbo: cannot read universe %s: %s")
             % universe_json % e.what());
  }

  // Seed RefData with an empty universe CSV so add_future_asset can populate it
  // dynamically (same pattern as SimKaspr::load_universe).
  {
    const std::string seed = "bin_replay_bbo_universe_seed.csv";
    std::ofstream f(seed);
    ASSERTF(f.is_open(), boost::format("cannot write %s") % seed);
    f << "# generated by bin_replay_bbo; instruments come from " << universe_json << "\n";
    f.close();
    frame::ref::RefData::set_universe(seed);
    frame::ref::RefData::inst();
  }

  auto insts = pt.get_child_optional("instruments");
  if (!insts) ERRF(boost::format("universe %s has no 'instruments' key") % universe_json);

  std::vector<Contract> out;
  size_t skipped_no_limit = 0, skipped_filter = 0, skipped_type = 0;

  for (const auto &kv : *insts) {
    const auto &inst = kv.second;
    if (inst.get<std::string>("type", "") != "FDF") { ++skipped_type; continue; }
    if (inst.get<std::string>("securityType", "") != "FUT") { ++skipped_type; continue; }

    const auto sec_id = inst.get<int32_t>("securityID", 0);
    const auto sym    = inst.get<std::string>("symbol", "");
    if (sec_id == 0 || sym.empty()) continue;

    // high_limit_px sizes the OB ladder. Options and some inter-commodity
    // spreads ship a null here; skip them rather than fail late in OB
    // construction.
    const auto hi = inst.get<double>("high_limit_px", 0.0);
    if (!(hi > 0.0)) { ++skipped_no_limit; continue; }

    const auto asset_root = inst.get<std::string>("asset", "");
    if (!asset_filter.empty() && asset_root != asset_filter) { ++skipped_filter; continue; }

    const auto cfi = inst.get<std::string>("cfiCode", "");
    const auto grp = inst.get<std::string>("securityGroup", "");
    const auto mpi = inst.get<double>("minPriceIncrement", 0.0);
    if (!(mpi > 0.0)) { ++skipped_no_limit; continue; }

    const auto vstr = inst.get<std::string>("venue", "");
    const en::x venue = vstr == "CMEMDFUT" ? en::x::CMEMDFUT
                      : vstr == "CMEMD"    ? en::x::CMEMD
                                           : default_venue;

    auto *a = frame::ref::RefData::add_future_asset(sym, venue, sec_id, cfi, grp, mpi);
    if (!a) continue;
    a->maxpx = static_cast<int>(hi / mpi);

    out.push_back(Contract{sym, asset_root, sec_id, mpi, hi, venue});
  }

  std::cerr << "bin_replay_bbo: universe " << universe_json << ":\n"
            << "  kept        : " << out.size() << "\n"
            << "  skip nolim  : " << skipped_no_limit << "\n"
            << "  skip type   : " << skipped_type << "\n"
            << "  skip filter : " << skipped_filter
            << (asset_filter.empty() ? "" : (" (asset != " + asset_filter + ")")) << "\n";

  return out;
}

// Manager that owns the actor graph: OBs, BboRecorder, BFA.
class BinReplayBbo : public actors::Manager
{
public:
  BinReplayBbo(const std::string &datafile,
               const std::string &universe_json,
               const std::string &out_path,
               const std::string &asset_filter,
               en::x default_venue,
               const std::string &session_date)
      : Manager("bin_replay_bbo_manager"),
        datafile_(datafile),
        universe_json_(universe_json),
        out_path_(out_path),
        session_date_(session_date)
  {
    logger_ = new polonaise::logger::act::Logger("bin_replay_bbo_log", nullptr);
    add_to_manage_q(logger_);

    group_ = new actors::Group("bin_replay_bbo_group");

    // 1) Universe.
    auto contracts = load_universe(universe_json_, asset_filter, default_venue);
    ASSERTF(!contracts.empty(),
            boost::format("bin_replay_bbo: no matching contracts in %s"
                          " (asset filter='%s')")
                % universe_json_ % asset_filter);

    // 2) OBs, one per contract, keyed [venue][asset_id]. This is the DENSE
    //    layout SimKaspr uses internally; we still convert to BFA's
    //    [venue][securityID] adapter below.
    const auto num_venues = en::x_num_syms();
    size_t max_id = 0;
    for (const auto &c : contracts)
      if (auto *a = frame::ref::RefData::get_asset(c.symbol))
        max_id = std::max(max_id, static_cast<size_t>(a->id));

    std::vector<std::vector<actors::Actor*>> order_books(num_venues);
    for (auto &row : order_books) row.resize(max_id + 1, nullptr);

    boost::property_tree::ptree pt_model;

    for (const auto &c : contracts) {
      auto *a = frame::ref::RefData::get_asset(c.symbol);
      if (!a) continue;
      const auto j = static_cast<size_t>(a->id);
      ASSERTF(a->maxpx > 1,
              boost::format("%s (secID %d) missing high_limit_px -- rebuild the universe")
                  % a->name % a->sec_id);
      // Manager is passed nullptr so OB::start_handler skips its SOM lookup
      // (that lookup throws when no SOM actor exists, and we deliberately do
      // not spin one up -- this driver only records, never routes orders).
      // `som` stays default-constructed; every use in OB.cpp is guarded by
      // `if (som)` so the unset ActorRef is treated as "no SOM wired".
      auto *ob = new frame::ob::act::OB(
          nullptr,     // no BinRecorder wired -- we tape via BBBOSub, not raw MBO
          false,       // do_cross_check: off (recording, not simulating)
          nullptr,     // manager: nullptr => skip SOM lookup on Start
          j,           // sym == asset id
          pt_model);
      group_->add(ob);
      order_books[c.venue][j] = ob;
      obs_.push_back(ob);
      ob_syms_.push_back(a->name);
    }

    std::cerr << "bin_replay_bbo: created " << obs_.size() << " order books" << std::endl;

    // 3) BboRecorder. Added to the same group as the OBs so the BBBOSub
    //    message it sends on Start is delivered to each OB's queue before BFA
    //    (added last) starts feeding Data. Group threads deliver Start messages
    //    to member actors in add() order.
    bbo_rec_ = create_BboRecorder(out_path_, session_date_, obs_);
    group_->add(bbo_rec_);

    // 4) BFA: keyed by securityID exactly like SimKaspr::create_bfa (see the
    //    comment there about why we do NOT use interface/mda/if/BFA.hpp's
    //    create_BFA -- that wrapper collapses on asset_id != sec_id).
    std::vector<std::unordered_map<int32_t, actor_ptr>> adapter(num_venues);
    for (size_t i = 0; i < obs_.size(); ++i) {
      auto *a = frame::ref::RefData::get_asset(ob_syms_[i]);
      if (!a) continue;
      const auto a_venue = a->is_exchange_md_set() ? a->get_exchange_md() : default_venue;
      ASSERTF(size_t(a_venue.value) < adapter.size(),
              boost::format("venue %d out of range for %s")
                  % int(a_venue.value) % a->name);
      adapter[a_venue][static_cast<int32_t>(a->sec_id)] = obs_[i];
    }

    bfa_ = new frame::mda::act::BFA<false>(
        adapter, datafile_, this,
        frame::mda::act::NoOpFactory{},
        false /*flip_sym_asset*/,
        0.0 /*time_warp*/,
        0, 0,   // tw hour/minute
        -1, -1, // start/end hour (whole file)
        0);     // end_ts
    group_->add(bfa_);   // last -- BFA starts pumping Data after every OB and
                         // the recorder are ready to receive.

    add_to_manage_q(group_);
  }

private:
  std::string datafile_;
  std::string universe_json_;
  std::string out_path_;
  std::string session_date_;

  actors::Group *group_ = nullptr;
  actors::Actor *logger_ = nullptr;
  actors::Actor *bfa_ = nullptr;
  actors::Actor *bbo_rec_ = nullptr;

  std::vector<actors::Actor*> obs_;
  std::vector<std::string>    ob_syms_;
};

} // namespace

int main(int argc, char *argv[])
{
  SET_ARGS;
  PRINT_ARGS;
  tzset();

  ::signal(SIGSEGV, &my_signal_handler);
  ::signal(SIGABRT, &my_signal_handler);
  ::signal(SIGBUS,  &my_signal_handler);
  ::signal(SIGFPE,  &my_signal_handler);
  ::signal(SIGPIPE, SIG_IGN);

  std::cout << argv[0] << std::endl;
  std::cout << boost::filesystem::current_path() << std::endl;
  std::cout << "pid: " << getpid() << std::endl;

  po::options_description desc("bin_replay_bbo options");
  desc.add_options()
      ("help",     "produce help message")
      ("datafile", po::value<std::string>(), "gzipped L3 .bin to replay (required)")
      ("universe", po::value<std::string>(), "per-day universe JSON (required); see "
                                              "dbento_pcap_parse/scripts/build_universe_day.sh")
      ("out",      po::value<std::string>(), "output CSV(.gz), required. Compressed gzip.")
      ("asset",    po::value<std::string>()->default_value(""),
                   "only trace contracts under this asset root (e.g. NQ). Empty = every "
                   "FDF/FUT in the universe that has a valid high_limit_px.")
      ("venue",    po::value<std::string>()->default_value("CMEMD"),
                   "default en::x venue name for entries whose universe row omits it "
                   "(CMEMD or CMEMDFUT).")
      ("session",  po::value<std::string>()->default_value(""),
                   "session date label written to the log; empty = extract YYYYMMDD "
                   "from the datafile name.")
      ("logdebug", "enable debug logs")
      ("quiet",    "log only errors/warnings");

  po::variables_map vm;
  po::store(po::parse_command_line(argc, argv, desc), vm);
  po::notify(vm);

  if (vm.count("help") || argc == 1) {
    std::cout << desc << "\n\nExample:\n"
              << "  ./bin_replay_bbo \\\n"
              << "    --datafile /vast/home/vmayeski/out/bin/318/318.20250310.databento.bin \\\n"
              << "    --universe /home/vmayeski/kaspar-hft/dbento_pcap_parse/scripts/out/universe/318/universe.318.20250310.json \\\n"
              << "    --out bbo.318.20250310.csv.gz --asset NQ\n";
    return 1;
  }
  if (!vm.count("datafile")) { std::cerr << "Error: --datafile required\n"; return 1; }
  if (!vm.count("universe")) { std::cerr << "Error: --universe required\n"; return 1; }
  if (!vm.count("out"))      { std::cerr << "Error: --out required\n";      return 1; }

  const auto datafile = vm["datafile"].as<std::string>();
  const auto universe = vm["universe"].as<std::string>();
  const auto out_path = vm["out"].as<std::string>();
  const auto asset    = vm["asset"].as<std::string>();

  const auto venue_str = vm["venue"].as<std::string>();
  const en::x default_venue = (venue_str == "CMEMDFUT") ? en::x::CMEMDFUT : en::x::CMEMD;

  std::string session = vm["session"].as<std::string>();
  if (session.empty()) session = date_from_datafile(datafile);
  if (session.empty()) session = "unknown";

  polonaise::logger::act::Logger::rt = true;
  polonaise::logger::act::Logger::log_debug  = vm.count("logdebug") > 0;
  polonaise::logger::act::Logger::quiet      = vm.count("quiet") > 0;
  polonaise::logger::act::Logger::synchrolog = vm.count("logdebug") > 0;

  std::cerr << "bin_replay_bbo: datafile=" << datafile << "\n"
            << "                universe=" << universe << "\n"
            << "                out     =" << out_path << "\n"
            << "                asset   =" << (asset.empty() ? "<all>" : asset) << "\n"
            << "                venue   =" << venue_str << "\n"
            << "                session =" << session << std::endl;

  BinReplayBbo *mgr = nullptr;
  try {
    mgr = new BinReplayBbo(datafile, universe, out_path, asset, default_venue, session);
  } catch (const std::exception &e) {
    std::cerr << "ERROR constructing BinReplayBbo: " << e.what() << std::endl;
    return 1;
  }

#ifndef __APPLE__
  feenableexcept(FE_DIVBYZERO | FE_OVERFLOW | FE_INVALID);
#endif

  auto thrd = boost::thread(boost::ref(*mgr));
  thrd.join();

  std::cout << "=== bin_replay_bbo complete ===" << std::endl;
  return 0;
}
