
# Copyright (c) 2026 Vincent Mayeski / M2 Tech (16425640 Canada Inc.).
#
# Licensed under the MIT License. See LICENSE file in the project root.

include $(KSPRPROJ)/mk_kaspr/glob_begin.mk

LIBSRC = ilink_handler.cpp ilink_rec.cpp ilink_arbiter.cpp

NAM = ilink

include $(KSPRPROJ)/mk_kaspr/lib_template.mk
