
# Copyright (c) 2026 Vincent Mayeski / M2 Tech (16425640 Canada Inc.).
#
# Licensed under the MIT License. See LICENSE file in the project root.

include $(KSPRPROJ)/mk_kaspr/glob_begin.mk

LIBSRC = message_processor.cpp msgbuf.cpp recoveryprocessor.cpp socketreader.cpp instrumentrecorder.cpp recoveryrecorder.cpp

NAM = mdp3

include $(KSPRPROJ)/mk_kaspr/lib_template.mk
