// AUTO-GENERATED by interop/codegen/generate.py — DO NOT EDIT.
// Regenerate: python3 interop/codegen/generate.py
//
// Source of truth: interop/messages/interop_messages.h
#![allow(dead_code)]

use std::os::raw::{c_char, c_int, c_void};

use crate::actor::ActorRef;
use crate::interop::{cpp_ref, register_cpp_lookup, register_inbound, resolve_local, NameBuf};
use crate::message::Message;

pub const INTEROP_STRING_MAX: usize = 64;

/// Wire form of a string (mirrors C `interop_string`): fixed buffer + length.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct CInteropString {
    pub data: [u8; INTEROP_STRING_MAX],
    pub len: u32,
}

impl Default for CInteropString {
    fn default() -> Self {
        CInteropString { data: [0u8; INTEROP_STRING_MAX], len: 0 }
    }
}

impl CInteropString {
    fn from_str(s: &str) -> Self {
        let mut out = Self::default();
        let n = s.len().min(INTEROP_STRING_MAX - 1);
        out.data[..n].copy_from_slice(&s.as_bytes()[..n]);
        out.len = n as u32;
        out
    }
    fn decode(self) -> String {
        let n = (self.len as usize).min(INTEROP_STRING_MAX);
        String::from_utf8_lossy(&self.data[..n]).into_owned()
    }
}

// ---- Ping (id 400) ------------------------------------
#[repr(C)]
#[derive(Clone, Copy)]
pub struct CPing {
    pub count: i32,
}

#[derive(Clone, Debug, Default)]
pub struct Ping {
    pub count: i32,
}
crate::define_message!(Ping, 400);

impl Ping {
    pub fn to_c(&self) -> CPing {
        CPing {
            count: self.count,
        }
    }
    pub fn from_c(c: &CPing) -> Self {
        Ping {
            count: c.count,
        }
    }
}

// ---- Pong (id 401) ------------------------------------
#[repr(C)]
#[derive(Clone, Copy)]
pub struct CPong {
    pub count: i32,
}

#[derive(Clone, Debug, Default)]
pub struct Pong {
    pub count: i32,
}
crate::define_message!(Pong, 401);

impl Pong {
    pub fn to_c(&self) -> CPong {
        CPong {
            count: self.count,
        }
    }
    pub fn from_c(c: &CPong) -> Self {
        Pong {
            count: c.count,
        }
    }
}

// ---- DataRequest (id 402) -----------------------------
#[repr(C)]
#[derive(Clone, Copy)]
pub struct CDataRequest {
    pub request_id: i32,
    pub symbol: CInteropString,
}

#[derive(Clone, Debug, Default)]
pub struct DataRequest {
    pub request_id: i32,
    pub symbol: String,
}
crate::define_message!(DataRequest, 402);

impl DataRequest {
    pub fn to_c(&self) -> CDataRequest {
        CDataRequest {
            request_id: self.request_id,
            symbol: CInteropString::from_str(&self.symbol),
        }
    }
    pub fn from_c(c: &CDataRequest) -> Self {
        DataRequest {
            request_id: c.request_id,
            symbol: c.symbol.decode(),
        }
    }
}

// ---- DataResponse (id 403) ----------------------------
#[repr(C)]
#[derive(Clone, Copy)]
pub struct CDataResponse {
    pub request_id: i32,
    pub value: f64,
    pub found: i32,
}

#[derive(Clone, Debug, Default)]
pub struct DataResponse {
    pub request_id: i32,
    pub value: f64,
    pub found: bool,
}
crate::define_message!(DataResponse, 403);

impl DataResponse {
    pub fn to_c(&self) -> CDataResponse {
        CDataResponse {
            request_id: self.request_id,
            value: self.value,
            found: if self.found { 1 } else { 0 },
        }
    }
    pub fn from_c(c: &CDataResponse) -> Self {
        DataResponse {
            request_id: c.request_id,
            value: c.value,
            found: c.found != 0,
        }
    }
}

// C++ bridge entry points — implemented in C++, resolved at final link time.
// The pure-Rust interop test links tiny stubs for these instead.
extern "C" {
    fn cpp_actor_send(actor: *const c_char, sender: *const c_char, id: c_int, data: *const c_void) -> c_int;
    fn cpp_actor_fast_send(actor: *const c_char, sender: *const c_char, id: c_int, data: *const c_void) -> c_int;
    fn cpp_actor_exists(actor: *const c_char) -> c_int;
}

/// Inbound dispatch (C++ -> Rust): rebuild the message from its C struct and
/// deliver it to the named local actor. Registered as the framework `InboundFn`.
fn interop_inbound(name: &str, _sender: &str, msg_id: i32, data: *const c_void, fast: bool) -> i32 {
    let target = match resolve_local(name) {
        Some(t) => t,
        None => return -1, // no such local actor
    };
    match msg_id {
        400 => {
            let c = unsafe { &*(data as *const CPing) };
            let m = Ping::from_c(c);
            if fast {
                target.fast_send(&m, None);
            } else {
                target.send(Box::new(m), None);
            }
            0
        }
        401 => {
            let c = unsafe { &*(data as *const CPong) };
            let m = Pong::from_c(c);
            if fast {
                target.fast_send(&m, None);
            } else {
                target.send(Box::new(m), None);
            }
            0
        }
        402 => {
            let c = unsafe { &*(data as *const CDataRequest) };
            let m = DataRequest::from_c(c);
            if fast {
                target.fast_send(&m, None);
            } else {
                target.send(Box::new(m), None);
            }
            0
        }
        403 => {
            let c = unsafe { &*(data as *const CDataResponse) };
            let m = DataResponse::from_c(c);
            if fast {
                target.fast_send(&m, None);
            } else {
                target.send(Box::new(m), None);
            }
            0
        }
        _ => -2, // unknown message id
    }
}

/// Outbound marshalling (Rust -> C++), send. Registered via `cpp_ref`.
fn cpp_outbound_send(target: &str, sender: &str, msg: &dyn Message) -> i32 {
    let t = NameBuf::new(target);
    let s = NameBuf::new(sender);
    match msg.message_id() {
        400 => match msg.as_any().downcast_ref::<Ping>() {
            Some(m) => {
                let c = m.to_c();
                unsafe { cpp_actor_send(t.as_ptr(), s.as_ptr(), 400, &c as *const _ as *const c_void) }
            }
            None => -2,
        },
        401 => match msg.as_any().downcast_ref::<Pong>() {
            Some(m) => {
                let c = m.to_c();
                unsafe { cpp_actor_send(t.as_ptr(), s.as_ptr(), 401, &c as *const _ as *const c_void) }
            }
            None => -2,
        },
        402 => match msg.as_any().downcast_ref::<DataRequest>() {
            Some(m) => {
                let c = m.to_c();
                unsafe { cpp_actor_send(t.as_ptr(), s.as_ptr(), 402, &c as *const _ as *const c_void) }
            }
            None => -2,
        },
        403 => match msg.as_any().downcast_ref::<DataResponse>() {
            Some(m) => {
                let c = m.to_c();
                unsafe { cpp_actor_send(t.as_ptr(), s.as_ptr(), 403, &c as *const _ as *const c_void) }
            }
            None => -2,
        },
        _ => -2,
    }
}

/// Outbound marshalling (Rust -> C++), fast. Registered via `cpp_ref`.
fn cpp_outbound_fast(target: &str, sender: &str, msg: &dyn Message) -> i32 {
    let t = NameBuf::new(target);
    let s = NameBuf::new(sender);
    match msg.message_id() {
        400 => match msg.as_any().downcast_ref::<Ping>() {
            Some(m) => {
                let c = m.to_c();
                unsafe { cpp_actor_fast_send(t.as_ptr(), s.as_ptr(), 400, &c as *const _ as *const c_void) }
            }
            None => -2,
        },
        401 => match msg.as_any().downcast_ref::<Pong>() {
            Some(m) => {
                let c = m.to_c();
                unsafe { cpp_actor_fast_send(t.as_ptr(), s.as_ptr(), 401, &c as *const _ as *const c_void) }
            }
            None => -2,
        },
        402 => match msg.as_any().downcast_ref::<DataRequest>() {
            Some(m) => {
                let c = m.to_c();
                unsafe { cpp_actor_fast_send(t.as_ptr(), s.as_ptr(), 402, &c as *const _ as *const c_void) }
            }
            None => -2,
        },
        403 => match msg.as_any().downcast_ref::<DataResponse>() {
            Some(m) => {
                let c = m.to_c();
                unsafe { cpp_actor_fast_send(t.as_ptr(), s.as_ptr(), 403, &c as *const _ as *const c_void) }
            }
            None => -2,
        },
        _ => -2,
    }
}

/// Resolve a name to a C++ actor over FFI (used by `Manager::get_ref`).
fn cpp_lookup(name: &str, sender: &str) -> Option<ActorRef> {
    let nb = NameBuf::new(name);
    if unsafe { cpp_actor_exists(nb.as_ptr()) } != 0 {
        Some(cpp_ref(name, sender, cpp_outbound_send, cpp_outbound_fast))
    } else {
        None
    }
}

/// Install the generated inbound dispatcher and C++ resolver. Call once at
/// startup, after `register_local_lookup(...)`.
pub fn register() {
    register_inbound(interop_inbound);
    register_cpp_lookup(cpp_lookup);
}
