#!/usr/bin/env python3

# Copyright (c) 2026 Vincent Mayeski / M2 Tech (16425640 Canada Inc.).
# Contact: v@m2te.ch | https://www.linkedin.com/in/vmayeski/
#
# Licensed under the MIT License. See LICENSE file in the project root.

import os
import fnmatch
import sys
import re
from pathlib import Path
from typing import List, Tuple, Optional
from dataclasses import dataclass

# Configuration
OUTDIR = "../../include/enum"
NAMESPACE = "en"


@dataclass
class EnumItem:
    """Represents a single enum value"""
    name: str
    value: Optional[str] = None

    def __str__(self):
        return f"{self.name}={self.value}" if self.value else self.name

    def display_name(self) -> str:
        """Get the display name for string lookups (strips leading underscore)"""
        if self.name.startswith('_') and len(self.name) > 1:
            return self.name[1:]  # Strip leading underscore for display
        return self.name


@dataclass
class EnumMetadata:
    """Contains all metadata for an enum definition"""
    name: str
    prefix: str
    items: List[EnumItem]

    def __post_init__(self):
        self.validate()

    def validate(self):
        """Validate enum metadata"""
        if not self.prefix:
            raise ValueError(f"Enum {self.name} has empty prefix")
        if not self.items:
            raise ValueError(f"Enum {self.name} has no items")

        # Check for duplicates
        names = [item.name for item in self.items]
        if len(names) != len(set(names)):
            duplicates = {n for n in names if names.count(n) > 1}
            raise ValueError(f"Enum {self.name} has duplicate items: {duplicates}")

    def num_items(self) -> int:
        return len(self.items)

    def has_uni(self) -> bool:
        """Check if enum has UNI special value"""
        return any(item.name == "UNI" for item in self.items)

    def items_before_uni(self) -> List[EnumItem]:
        """Get all items before UNI marker"""
        result = []
        for item in self.items:
            if item.name == "UNI":
                break
            result.append(item)
        return result


class CppCodeGenerator:
    """Generates modern C++ code for enums"""

    def __init__(self, namespace: str = "en"):
        self.namespace = namespace

    def generate(self, enum: EnumMetadata) -> str:
        """Generate complete C++ header file"""
        parts = [
            self._generate_header(),
            self._generate_namespace_open(),
            self._generate_struct(enum),
            self._generate_constexpr_data(enum),
            self._generate_array_wrapper(enum),
            self._generate_functions(enum),
            self._generate_operators(enum),
            self._generate_namespace_close(),
            self._generate_hash_specialization(enum)
        ]
        return '\n'.join(parts)

    def _generate_header(self) -> str:
        return """// ============================================================================
// GENERATED CODE - DO NOT MODIFY
// This file is automatically generated by genenum.py
// To modify this enum, edit the corresponding .enum file in:
//     chutil/gencode/enum/def/
// Then regenerate by running:
//     cd chutil/gencode/enum && ./genenum.py
// ============================================================================

#pragma once
#include <array>
#include <string_view>
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <optional>
#include <limits>
#include "chutil/Macros.hpp"
"""

    def _generate_namespace_open(self) -> str:
        return f"namespace {self.namespace} {{\n"

    def _generate_namespace_close(self) -> str:
        return "}\n"

    def _generate_struct(self, enum: EnumMetadata) -> str:
        """Generate the enum struct"""
        lines = [f"\nstruct {enum.prefix} {{"]
        lines.append("    std::uint32_t value;")
        lines.append("    enum {")

        for i, item in enumerate(enum.items):
            line = f"        {item.name}"
            if item.value:
                line += f"={item.value}"
            if i < len(enum.items) - 1:
                line += ","
            lines.append(line)

        lines.append("    };")
        lines.append("")
        lines.append("    // Implicit conversion to uint for backward compatibility")
        lines.append("    constexpr operator std::uint32_t() const { return value; }")
        lines.append("    // Default constructor")
        lines.append(f"    constexpr {enum.prefix}() : value(std::numeric_limits<std::uint32_t>::max()) {{}}")
        lines.append("    // Constructors from enum values (use implicit uint conversion)")
        lines.append(f"    constexpr {enum.prefix}(std::uint32_t _value) : value(_value) {{}}")
        lines.append("};")

        return '\n'.join(lines)

    def _generate_constexpr_data(self, enum: EnumMetadata) -> str:
        """Generate constexpr lookup tables"""
        lines = [f"\n// Constexpr lookup tables for {enum.prefix}"]

        # Name array - using const char* for better compatibility
        # Use display_name() to strip leading underscores (e.g., "_2Y" -> "2Y")
        lines.append(f"inline constexpr std::array<const char*, {enum.num_items()}> {enum.prefix}_names = {{{{")
        for item in enum.items:
            lines.append(f'    "{item.display_name()}",')
        lines.append("}};")

        # Value array
        lines.append(f"\ninline constexpr std::array<std::uint32_t, {enum.num_items()}> {enum.prefix}_values = {{{{")
        for item in enum.items:
            lines.append(f"    {enum.prefix}::{item.name},")
        lines.append("}};")

        # All values (excluding UNI)
        valid_items = enum.items_before_uni()
        if valid_items:
            lines.append(f"\ninline constexpr std::array<std::uint32_t, {len(valid_items)}> {enum.prefix}_all = {{{{")
            for item in valid_items:
                lines.append(f"    {enum.prefix}::{item.name},")
            lines.append("}};")

        # Pair type for iteration (backward compatibility with map iteration)
        lines.append(f"\nusing {enum.prefix}_pair = std::pair<{enum.prefix}, const char*>;")

        # Name-value pairs for iteration
        # Use display_name() for string part to strip leading underscores
        lines.append(f"\ninline constexpr std::array<{enum.prefix}_pair, {enum.num_items()}> {enum.prefix}_name_hash = {{{{")
        for item in enum.items:
            lines.append(f'    {enum.prefix}_pair{{{enum.prefix}::{item.name}, "{item.display_name()}"}},')
        lines.append("}};")

        return '\n'.join(lines)

    def _generate_array_wrapper(self, enum: EnumMetadata) -> str:
        """Generate type-safe array wrapper template"""
        lines = [f"\n// Type-safe array indexed by {enum.prefix}"]
        lines.append(f"template<typename T>")
        lines.append(f"struct {enum.prefix}_array {{")
        lines.append(f"    std::array<T, {enum.num_items()}> data;")
        lines.append("")
        lines.append(f"    // Access operators")
        lines.append(f"    constexpr T& operator[]({enum.prefix} idx) {{ return data[idx.value]; }}")
        lines.append(f"    constexpr const T& operator[]({enum.prefix} idx) const {{ return data[idx.value]; }}")
        lines.append("")
        lines.append(f"    constexpr T& at({enum.prefix} idx) {{")
        lines.append(f"        if (idx.value >= data.size()) throw std::out_of_range(\"{enum.prefix}_array::at\");")
        lines.append(f"        return data[idx.value];")
        lines.append(f"    }}")
        lines.append(f"    constexpr const T& at({enum.prefix} idx) const {{")
        lines.append(f"        if (idx.value >= data.size()) throw std::out_of_range(\"{enum.prefix}_array::at\");")
        lines.append(f"        return data[idx.value];")
        lines.append(f"    }}")
        lines.append("")
        lines.append(f"    // Standard container interface")
        lines.append(f"    constexpr auto begin() {{ return data.begin(); }}")
        lines.append(f"    constexpr auto end() {{ return data.end(); }}")
        lines.append(f"    constexpr auto begin() const {{ return data.begin(); }}")
        lines.append(f"    constexpr auto end() const {{ return data.end(); }}")
        lines.append(f"    constexpr auto cbegin() const {{ return data.cbegin(); }}")
        lines.append(f"    constexpr auto cend() const {{ return data.cend(); }}")
        lines.append(f"    constexpr std::size_t size() const {{ return data.size(); }}")
        lines.append(f"    constexpr bool empty() const {{ return false; }}")
        lines.append(f"    constexpr T& front() {{ return data.front(); }}")
        lines.append(f"    constexpr const T& front() const {{ return data.front(); }}")
        lines.append(f"    constexpr T& back() {{ return data.back(); }}")
        lines.append(f"    constexpr const T& back() const {{ return data.back(); }}")
        lines.append(f"    constexpr T* ptr() {{ return data.data(); }}")
        lines.append(f"    constexpr const T* ptr() const {{ return data.data(); }}")
        lines.append("};")

        return '\n'.join(lines)

    def _generate_functions(self, enum: EnumMetadata) -> str:
        """Generate utility functions"""
        lines = [f"\n// Utility functions for {enum.prefix}"]

        # to_string using constexpr array - returns const char* for backward compatibility with string concatenation
        lines.append(f"\nINLINE constexpr const char* to_string({enum.prefix} n) {{")
        lines.append(f"    if (static_cast<std::size_t>(n.value) < {enum.prefix}_names.size()) {{")
        lines.append(f"        return {enum.prefix}_names[n.value];")
        lines.append("    }")
        lines.append('    return "INVALID";')
        lines.append("}")

        # num_syms
        lines.append(f"\nINLINE constexpr std::size_t {enum.prefix}_num_syms() {{")
        lines.append(f"    return {enum.num_items()};")
        lines.append("}")

        # is_valid
        if enum.has_uni():
            lines.append(f"\nINLINE constexpr bool is_valid({enum.prefix} n) {{")
            lines.append(f"    return (n.value < {enum.prefix}_num_syms() && n.value != {enum.prefix}::UNI);")
            lines.append("}")
        else:
            lines.append(f"\nINLINE constexpr bool is_valid({enum.prefix} n) {{")
            lines.append(f"    return n.value < {enum.prefix}_num_syms();")
            lines.append("}")

        # String-based validation
        lines.append(f"\nINLINE bool {enum.prefix}_is_valid(std::string_view nam) {{")
        lines.append(f"    return std::find({enum.prefix}_names.begin(), {enum.prefix}_names.end(), nam) != {enum.prefix}_names.end();")
        lines.append("}")

        # Parse from string with error
        lines.append(f"\nINLINE {enum.prefix} {enum.prefix}_index_of(std::string_view str) {{")
        lines.append(f"    auto it = std::find({enum.prefix}_names.begin(), {enum.prefix}_names.end(), str);")
        lines.append(f"    if (it == {enum.prefix}_names.end()) {{")
        lines.append('        std::cerr << str << " not found" << std::endl;')
        lines.append('        ERR("not found");')
        lines.append("    }")
        lines.append(f"    return {enum.prefix}(static_cast<std::uint32_t>(it - {enum.prefix}_names.begin()));")
        lines.append("}")

        # Try parse from string (returns optional)
        lines.append(f"\nINLINE std::optional<{enum.prefix}> {enum.prefix}_try_parse(std::string_view str) {{")
        lines.append(f"    auto it = std::find({enum.prefix}_names.begin(), {enum.prefix}_names.end(), str);")
        lines.append(f"    if (it == {enum.prefix}_names.end()) {{")
        lines.append("        return std::nullopt;")
        lines.append("    }")
        lines.append(f"    return {enum.prefix}(static_cast<std::uint32_t>(it - {enum.prefix}_names.begin()));")
        lines.append("}")

        # Map-like wrapper for backward compatibility (provides .contains(), .find(), etc.)
        lines.append(f"\nstruct {enum.prefix}_hash_t {{")
        lines.append(f"    bool contains(std::string_view key) const {{")
        lines.append(f"        return std::find({enum.prefix}_names.begin(), {enum.prefix}_names.end(), key) != {enum.prefix}_names.end();")
        lines.append("    }")
        lines.append(f"    {enum.prefix} operator[](std::string_view key) const {{")
        lines.append(f"        return {enum.prefix}_index_of(key);")
        lines.append("    }")
        lines.append(f"    auto find(std::string_view key) const {{")
        lines.append(f"        auto it = std::find({enum.prefix}_names.begin(), {enum.prefix}_names.end(), key);")
        lines.append(f"        if (it != {enum.prefix}_names.end()) {{")
        lines.append(f"            return {enum.prefix}_name_hash.begin() + (it - {enum.prefix}_names.begin());")
        lines.append("        }")
        lines.append(f"        return {enum.prefix}_name_hash.end();")
        lines.append("    }")
        lines.append(f"    auto end() const {{ return {enum.prefix}_name_hash.end(); }}")
        lines.append("};")
        lines.append(f"inline const {enum.prefix}_hash_t {enum.prefix}_hash;")

        return '\n'.join(lines)

    def _generate_operators(self, enum: EnumMetadata) -> str:
        """Generate operator overloads"""
        lines = [f"\n// Operators for {enum.prefix}"]

        # Stream output operator
        lines.append(f"\nINLINE std::ostream& operator<<(std::ostream& out, const {enum.prefix}& p) {{")
        lines.append("    return out << to_string(p);")
        lines.append("}")

        # Note: Comparison operators use implicit uint32_t conversion to avoid ambiguity
        # The implicit conversion allows comparing enum struct with enum values seamlessly

        return '\n'.join(lines)

    def _generate_hash_specialization(self, enum: EnumMetadata) -> str:
        """Generate std::hash specialization for use with unordered_map/unordered_set"""
        return f"""
// std::hash specialization for use with std::unordered_map, std::unordered_set, etc.
namespace std {{
    template<> struct hash<{NAMESPACE}::{enum.prefix}> {{
        std::size_t operator()({NAMESPACE}::{enum.prefix} e) const noexcept {{
            return std::hash<std::uint32_t>{{}}(e.value);
        }}
    }};
}}
"""


class EnumParser:
    """Parses enum definition files"""

    @staticmethod
    def tokenize(string: str) -> List[str]:
        """Tokenize a line from enum file"""
        return re.split(r"[\s\:,()/]+", string.rstrip())

    @staticmethod
    def parse_file(filepath: str) -> EnumMetadata:
        """Parse an enum definition file"""
        name = Path(filepath).stem

        with open(filepath, 'r') as f:
            lines = f.readlines()

        if not lines:
            raise ValueError(f"Empty enum file: {filepath}")

        # Find first non-comment line for prefix
        prefix = None
        start_idx = 0
        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped and not stripped.startswith('#'):
                prefix = stripped.split()[0]  # Take first token, ignore comments after
                start_idx = i + 1
                break

        if not prefix:
            raise ValueError(f"No prefix found in {filepath}")

        items = []
        for line in lines[start_idx:]:
            stripped = line.strip()
            if stripped and not stripped.startswith('#'):  # Skip comments and empty lines
                tokens = EnumParser.tokenize(stripped)
                if tokens and tokens[0]:
                    item_name = tokens[0]
                    item_value = tokens[1] if len(tokens) > 1 else None
                    items.append(EnumItem(item_name, item_value))

        return EnumMetadata(name=name, prefix=prefix, items=items)


def list_files(dir_path: str, pattern: str) -> List[str]:
    """List files matching pattern in directory"""
    files = []
    for f in os.listdir(dir_path):
        if fnmatch.fnmatch(f, pattern):
            full_path = os.path.join(dir_path, f)
            if os.path.isfile(full_path):
                files.append(full_path)
    return sorted(files)


def generate_master_header(enum_names: List[str], outdir: str):
    """Generate master header that includes all enum headers"""
    output_path = os.path.join(outdir, "e_names.hpp")

    with open(output_path, 'w') as f:
        f.write('// ============================================================================\n')
        f.write('// GENERATED CODE - DO NOT MODIFY\n')
        f.write('// This file is automatically generated by genenum.py\n')
        f.write('// To modify enums, edit the corresponding .enum files in:\n')
        f.write('//     chutil/gencode/enum/def/\n')
        f.write('// Then regenerate by running:\n')
        f.write('//     cd chutil/gencode/enum && ./genenum.py\n')
        f.write('// ============================================================================\n\n')
        f.write('#pragma once\n\n')
        f.write('#include "chutil/Macros.hpp"\n\n')

        for name in enum_names:
            f.write(f'#include "enum/{name}.hpp"\n')


def main():
    """Main entry point"""
    enum_dir = "./def/"
    output_dir = OUTDIR

    # Find all enum definition files
    enum_files = list_files(enum_dir, "*.enum")
    print(f"Found {len(enum_files)} enum files:")
    print(enum_files)

    enum_names = []
    parser = EnumParser()
    generator = CppCodeGenerator(NAMESPACE)

    # Process each enum file
    for filepath in enum_files:
        try:
            # Parse enum definition
            enum_meta = parser.parse_file(filepath)
            enum_names.append(enum_meta.name)

            print(f"\nProcessing {enum_meta.name} (prefix: {enum_meta.prefix})")
            print(f"  Items: {[item.name for item in enum_meta.items]}")

            # Generate C++ code
            cpp_code = generator.generate(enum_meta)

            # Write output file
            output_path = os.path.join(output_dir, f"{enum_meta.name}.hpp")
            with open(output_path, 'w') as f:
                f.write(cpp_code)

            print(f"  Generated: {output_path}")

        except Exception as e:
            print(f"Error processing {filepath}: {e}")
            raise

    # Generate master header
    generate_master_header(enum_names, output_dir)
    print(f"\nGenerated master header: {output_dir}/e_names.hpp")


if __name__ == "__main__":
    main()
