# Copyright (c) 2026 Vincent Mayeski / M2 Tech (16425640 Canada Inc.).
#
# Licensed under the MIT License. See LICENSE file in the project root.

NAM=frame

include $(KSPRPROJ)/mk_kaspr/glob_begin.mk

EXTRA_INCL=-I$(KSPRPROJ)/frame_kaspr/include

LIBSRC = RefData.cpp Timer.cpp OB.cpp point.cpp SOM.cpp SOM_if.cpp Cons_if.cpp BFA_if.cpp BinRecorder_if.cpp OB_if.cpp Timer_if.cpp

include $(KSPRPROJ)/mk_kaspr/lib_template.mk
