# Copyright (c) 2026 Vincent Mayeski / M2 Tech (16425640 Canada Inc.).
#
# Licensed under the MIT License. See LICENSE file in the project root.

include $(KSPRPROJ)/mk_kaspr/glob_begin.mk

EXTRA_INCL=-I$(KSPRPROJ)/db/include

LIBSRC = DB.cpp

NAM = db

include $(KSPRPROJ)/mk_kaspr/lib_template.mk
